import {useState} from 'react';
import {KeyRound,ShieldCheck,Smartphone} from 'lucide-react';
import {toast} from 'sonner';
import {api} from './api';

export default function Account({me,refreshSession}:any){
const [setup,setSetup]=useState<any>(null),[code,setCode]=useState(''),[pw,setPw]=useState({current:'',next:'',again:''}),[off,setOff]=useState({password:'',code:''});
async function call(path:string,body:any,msg:string){try{const r=await api(path,body);toast.success(msg);await refreshSession();return r||true}catch(e:any){toast.error(e.message)}}
return <div className="account">
{me.must_change_password&&<div className="expiry expiry-warn"><KeyRound size={17}/><span>Hesabın geçici parolayla açıldı. Devam etmeden önce kendi parolanı belirle.</span></div>}
<section className="panel pad"><h2><KeyRound size={18}/>Parola</h2><p className="field-help">{me.email} · Parolan değişince diğer cihazlardaki oturumlar kapanır.</p><form className="form-grid" onSubmit={async e=>{e.preventDefault();if(pw.next!==pw.again){toast.error('Yeni parolalar eşleşmiyor.');return}if(await call('me/password',{current:pw.current,new:pw.next},'Parolan değiştirildi.'))setPw({current:'',next:'',again:''})}}><label>Mevcut parola<input type="password" autoComplete="current-password" required value={pw.current} onChange={e=>setPw({...pw,current:e.target.value})}/></label><label>Yeni parola · en az 10 karakter<input type="password" autoComplete="new-password" minLength={10} required value={pw.next} onChange={e=>setPw({...pw,next:e.target.value})}/></label><label>Yeni parola tekrar<input type="password" autoComplete="new-password" minLength={10} required value={pw.again} onChange={e=>setPw({...pw,again:e.target.value})}/></label><button className="primary">Parolayı değiştir</button></form></section>
<section className="panel pad"><h2><ShieldCheck size={18}/>İki aşamalı giriş</h2>{me.totp_enabled?<><p className="field-help"><span className="pill saved">Açık</span> Girişte parolana ek olarak doğrulama uygulamandaki kod istenir.</p><form className="form-grid" onSubmit={async e=>{e.preventDefault();if(await call('me/2fa/disable',off,'İki aşamalı giriş kapatıldı.'))setOff({password:'',code:''})}}><label>Parola<input type="password" required value={off.password} onChange={e=>setOff({...off,password:e.target.value})}/></label><label>Güncel kod<input inputMode="numeric" required value={off.code} onChange={e=>setOff({...off,code:e.target.value})}/></label><button className="secondary">Kapat</button></form></>:
!setup?<><p className="field-help">Google Authenticator, Microsoft Authenticator, 1Password veya Authy gibi bir uygulama ile hesabını koru. Şirket hesapları için önerilir.</p><button className="primary" onClick={async()=>{try{setSetup(await api('me/2fa/setup',{}))}catch(e:any){toast.error(e.message)}}}><Smartphone size={15}/>Kurulumu başlat</button></>:
<div className="totp-setup"><ol><li>Doğrulama uygulamanda <strong>yeni hesap ekle → kurulum anahtarı gir</strong> seçeneğini aç.</li><li>Bu anahtarı gir (zaman tabanlı): <code className="totp-secret">{setup.secret.match(/.{1,4}/g).join(' ')}</code> <a className="inline-link" href={setup.uri}>Telefondaysan uygulamada aç</a></li><li>Uygulamanın gösterdiği 6 haneli kodu aşağıya yaz.</li></ol><form className="member-add" onSubmit={async e=>{e.preventDefault();if(await call('me/2fa/enable',{code},'İki aşamalı giriş açıldı.')){setSetup(null);setCode('')}}}><input inputMode="numeric" autoComplete="one-time-code" placeholder="6 haneli kod" required value={code} onChange={e=>setCode(e.target.value)}/><button className="primary">Doğrula ve aç</button><button type="button" className="text-button" onClick={()=>setSetup(null)}>Vazgeç</button></form></div>}</section>
</div>}
