import {useState} from 'react';
import {KeyRound,ShieldCheck,Smartphone,MonitorSmartphone} from 'lucide-react';
import {toast} from 'sonner';
import {api} from './api';
import {t} from './i18n';

export default function Account({me,refreshSession}:any){
const [setup,setSetup]=useState<any>(null),[code,setCode]=useState(''),[pw,setPw]=useState({current:'',next:'',again:''}),[off,setOff]=useState({password:'',code:''}),[showDisable,setShowDisable]=useState(false);
async function call(path:string,body:any,msg:string){try{const r=await api(path,body);toast.success(msg);await refreshSession();return r||true}catch(e:any){toast.error(e.message)}}
return <div className="account">
{me.must_change_password&&<div className="expiry expiry-warn"><KeyRound size={17}/><span>{t('Hesabın geçici parolayla açıldı. Devam etmeden önce kendi parolanı belirle.')}</span></div>}
<section className="panel pad"><h2><KeyRound size={18}/>{t('Parola')}</h2><p className="field-help">{me.email} · {t('Parolan değişince diğer cihazlardaki oturumlar kapanır.')}</p><form className="form-grid" onSubmit={async e=>{e.preventDefault();if(pw.next!==pw.again){toast.error(t('Yeni parolalar eşleşmiyor.'));return}if(await call('me/password',{current:pw.current,new:pw.next},t('Parolan değiştirildi.')))setPw({current:'',next:'',again:''})}}><label>{t('Mevcut parola')}<input type="password" autoComplete="current-password" required value={pw.current} onChange={e=>setPw({...pw,current:e.target.value})}/></label><label>{t('Yeni parola · en az 10 karakter')}<input type="password" autoComplete="new-password" minLength={10} required value={pw.next} onChange={e=>setPw({...pw,next:e.target.value})}/></label><label>{t('Yeni parola tekrar')}<input type="password" autoComplete="new-password" minLength={10} required value={pw.again} onChange={e=>setPw({...pw,again:e.target.value})}/></label><button className="primary">{t('Parolayı değiştir')}</button></form></section>
<section className="panel pad"><h2><ShieldCheck size={18}/>{t('İki aşamalı giriş')}</h2>{me.totp_enabled?<><p className="field-help"><span className="pill saved">{t('Açık')}</span> {t('Hesabın korunuyor. Bundan sonraki girişlerde parolana ek olarak doğrulama uygulamandaki kod istenir.')}</p>{!showDisable?<button className="secondary account-disable-toggle" onClick={()=>setShowDisable(true)}>{t('İki aşamalı girişi kapat')}</button>:<div className="totp-disable"><p className="field-help">{t('Yalnızca iki aşamalı korumayı kapatmak istiyorsan parolanı ve doğrulama uygulamandaki güncel kodu gir.')}</p><form className="form-grid" onSubmit={async e=>{e.preventDefault();if(await call('me/2fa/disable',off,t('İki aşamalı giriş kapatıldı.'))){setOff({password:'',code:''});setShowDisable(false)}}}><label>{t('Mevcut parola')}<input type="password" autoComplete="current-password" required value={off.password} onChange={e=>setOff({...off,password:e.target.value})}/></label><label>{t('Doğrulama uygulamasındaki 6 haneli kod')}<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9 ]{6,7}" required value={off.code} onChange={e=>setOff({...off,code:e.target.value})}/></label><div className="account-disable-actions"><button className="secondary">{t("2FA'yı kapat")}</button><button type="button" className="text-button" onClick={()=>{setShowDisable(false);setOff({password:'',code:''})}}>{t('Vazgeç')}</button></div></form></div>}</>:
!setup?<><p className="field-help">{t('Google Authenticator, Microsoft Authenticator, 1Password veya Authy gibi bir uygulama ile hesabını koru. Şirket hesapları için önerilir.')}</p><button className="primary" onClick={async()=>{try{setSetup(await api('me/2fa/setup',{}))}catch(e:any){toast.error(t(e.message))}}}><Smartphone size={15}/>{t('Kurulumu başlat')}</button></>:
<div className="totp-setup"><ol><li>{t('Doğrulama uygulamanda yeni hesap ekle → kurulum anahtarı gir seçeneğini aç.')}</li><li>{t('Bu anahtarı gir (zaman tabanlı):')} <code className="totp-secret">{setup.secret.match(/.{1,4}/g).join(' ')}</code> <a className="inline-link" href={setup.uri}>{t('Telefondaysan uygulamada aç')}</a></li><li>{t('Uygulamanın gösterdiği 6 haneli kodu aşağıya yaz.')}</li></ol><form className="member-add" onSubmit={async e=>{e.preventDefault();if(await call('me/2fa/enable',{code},t('İki aşamalı giriş açıldı.'))){setSetup(null);setCode('')}}}><input inputMode="numeric" autoComplete="one-time-code" placeholder={t('6 haneli kod')} required value={code} onChange={e=>setCode(e.target.value)}/><button className="primary">{t('Doğrula ve aç')}</button><button type="button" className="text-button" onClick={()=>setSetup(null)}>{t('Vazgeç')}</button></form></div>}</section>
<section className="panel pad"><h2><MonitorSmartphone size={18}/>{t('Açık oturumlar')}</h2><p className="field-help">{t('Telefonunu kaybettiysen veya ortak bir bilgisayarda oturumun açık kaldıysa, bu cihaz dışındaki tüm tarayıcı ve uygulama oturumlarını kapat.')}</p><button className="secondary" onClick={()=>confirm(t('Bu cihaz dışındaki tüm oturumlar kapatılsın mı?'))&&call('me/sessions/revoke',{},t('Diğer cihazlardaki oturumlar kapatıldı.'))}>{t('Diğer cihazlardan çıkış yap')}</button></section>
</div>}
