import {useState} from 'react';
import {Layers3,ShieldCheck,Server} from 'lucide-react';
import {api,ApiError,isApp,serverUrl,setServer,checkServer} from './api';
import {t} from './i18n';

export default function Login({loading,onDone}:{loading:boolean;onDone:()=>void}){
const [server,setServerField]=useState(serverUrl()),[editingServer,setEditingServer]=useState(isApp&&!serverUrl()),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[code,setCode]=useState(''),[needsCode,setNeedsCode]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
async function saveServer(e:any){e.preventDefault();setBusy(true);setError('');try{setServer(await checkServer(server));setEditingServer(false)}catch(err:any){setError(err.message)}finally{setBusy(false)}}
async function submit(e:any){e.preventDefault();setBusy(true);setError('');try{await api('login',{email,password,code});setPassword('');setCode('');onDone()}catch(err:any){if(err instanceof ApiError&&err.data?.needs_code&&!needsCode){setNeedsCode(true)}else setError(err.message)}finally{setBusy(false)}}
return <div className="login-screen"><div className="panel login-card"><div className="brand"><span className="brand-icon"><Layers3/></span>akış.</div><h1>{t(loading?'Stüdyon açılıyor…':editingServer?'Sunucuna bağlan':needsCode?'İki aşamalı doğrulama':'Şirket hesabına giriş')}</h1>{!loading&&editingServer&&<form onSubmit={saveServer}><p className="field-help"><Server size={15}/> {t('Şirketinin Akış sunucusunun adresini gir. Bu adresi sistem yöneticinden alabilirsin.')}</p><label>{t('Sunucu adresi')}<input type="url" inputMode="url" autoCapitalize="off" autoCorrect="off" placeholder="https://akis.sirketin.com" required value={server} onChange={e=>setServerField(e.target.value)}/></label><button className="primary" disabled={busy}>{t(busy?'Bağlanıyor…':'Devam et')}</button></form>}{!loading&&!editingServer&&<form onSubmit={submit}>{!needsCode?<><label>{t('E-posta')}<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>{t('Parola')}<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label></>:<><p className="field-help"><ShieldCheck size={15}/> {t('Doğrulama uygulamandaki 6 haneli kodu gir.')}</p><label>{t('Doğrulama kodu')}<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9 ]{6,7}" autoFocus required value={code} onChange={e=>setCode(e.target.value)}/></label></>}<button className="primary" disabled={busy}>{t(busy?'Kontrol ediliyor…':needsCode?'Doğrula ve gir':'Giriş yap')}</button>{isApp&&!needsCode&&<button type="button" className="inline-link" onClick={()=>{setEditingServer(true);setError('')}}>{t('Sunucu')}: {serverUrl().replace(/^https?:\/\//,'')} · {t('değiştir')}</button>}{needsCode&&<button type="button" className="inline-link" onClick={()=>{setNeedsCode(false);setCode('');setError('')}}>{t('Geri dön')}</button>}</form>}{error&&<p className="error">{t(error)}</p>}</div></div>}
