import {useMemo,useState} from 'react';
import {FileText,RefreshCw,Image as ImageIcon,Check,X,CalendarClock,Pencil,Trash2,History,Copy,Search} from 'lucide-react';
import {toast} from 'sonner';
import {api,platforms,statuses,contentStatuses,outcomes,stages,inZone,mediaSrc} from './api';
import {t} from './i18n';

const filters=[{id:'all',name:'Tümü'},{id:'pending_approval',name:'Onay bekleyen'},{id:'scheduled',name:'Planlı'},{id:'attention',name:'Sorunlu'},{id:'draft',name:'Taslak / reddedilen'}];
function matches(p:any,f:string){if(f==='all')return true;if(f==='attention')return p.status==='attention'||p.deliveries.some((d:any)=>['failed','unknown'].includes(d.status));if(f==='draft')return ['draft','rejected'].includes(p.status);return p.status===f}

export default function Posts({posts,loading,refresh,can,tz,onEdit,onDuplicate,initialFilter='all'}:any){
const [filter,setFilter]=useState(initialFilter),[q,setQ]=useState('');
const needle=q.trim().toLocaleLowerCase('tr');
const shown=useMemo(()=>posts.filter((p:any)=>matches(p,filter)&&(!needle||[p.text,p.options?.template,p.created_by,p.asset?.filename].some(v=>v&&String(v).toLocaleLowerCase('tr').includes(needle)))),[posts,filter,needle]);
const stats=useMemo(()=>[{label:'Toplam içerik',value:posts.length},{label:'Onay bekleyen',value:posts.filter((p:any)=>p.status==='pending_approval').length},{label:'Planlı',value:posts.filter((p:any)=>p.status==='scheduled').length},{label:'Kontrol gerekiyor',value:posts.filter((p:any)=>matches(p,'attention')).length}],[posts]);
async function act(path:string,body:any,done:string,method?:string){try{await api(path,body,method);toast.success(done);await refresh()}catch(e:any){toast.error(t(e.message))}}
async function reject(p:any){const note=prompt(t('Reddetme nedeni (editör bu notu görecek):'));if(note===null)return;await act(`posts/${p.id}/reject`,{note},t('İçerik reddedildi, editöre not iletildi.'))}
return <><div className="stats">{stats.map(s=><div className="stat-card" key={s.label}><span>{t(s.label)}</span><strong>{s.value}</strong></div>)}</div>
<section className="panel"><div className="panel-head"><div className="filter-tabs" role="tablist">{filters.map(f=><button key={f.id} role="tab" aria-selected={filter===f.id} className={filter===f.id?'active':''} onClick={()=>setFilter(f.id)}>{t(f.name)}</button>)}</div><label className="search-field"><Search size={15}/><input type="search" placeholder={t('İçeriklerde ara')} aria-label={t('İçeriklerde ara')} value={q} onChange={e=>setQ(e.target.value)}/></label><button className="secondary" onClick={refresh}><RefreshCw size={14}/>{t('Yenile')}</button></div>
{loading?<div className="empty-state">{t('Gönderiler yükleniyor…')}</div>:!shown.length?<div className="empty-state"><FileText size={36}/><h3>{t(needle?'Aramana uyan içerik yok.':filter==='all'?'İlk paylaşımına yer ayırdık.':'Bu listede içerik yok.')}</h3><p>{t('Taslaklar, onaylar ve gönderim sonuçları burada görünecek.')}</p></div>:shown.map((p:any)=><article key={p.id} className="post-item">
<div className="post-meta"><span className={'pill status-'+p.status}>{t(contentStatuses[p.status]||p.status)}</span><span>{inZone(Math.floor(p.created/1000),tz)}</span>{p.created_by&&<span>{t('Hazırlayan')}: {p.created_by}</span>}{p.approved_by&&<span>{t('Onaylayan')}: {p.approved_by}</span>}{p.scheduled_at&&<span className="schedule"><CalendarClock size={14}/>{inZone(p.scheduled_at,tz)}</span>}</div>
<h3>{p.text||p.options.template||t('Medya paylaşımı')}</h3>
{p.asset&&<div className="post-media">{p.asset.url&&p.asset.mime_type?.startsWith('image/')?<img className="post-media-preview" src={mediaSrc(p.asset.url)} alt={p.asset.filename} loading="lazy" decoding="async"/>:<ImageIcon size={15}/>}<span>{p.asset.filename}<small>{p.asset.note||t('Hazırlanıyor…')}</small></span></div>}
{p.review_note&&<p className={'review-note '+(p.status==='rejected'?'rejected':'')}>{t(p.status==='rejected'?'Red nedeni':'Onay notu')}: {p.review_note}</p>}
<div className="post-channels">{p.platforms.map((id:string)=><span key={id} className="pill">{platforms.find(x=>x.id===id)?.name}</span>)}</div>
{p.deliveries.length>0&&<div className="delivery-list">{p.deliveries.map((d:any)=><div key={d.id} className={'delivery '+d.status}><div className="delivery-heading"><strong>{platforms.find(x=>x.id===d.platform)?.name}</strong><span>{t(statuses[d.status]||d.status)}</span></div>{d.recipient&&<small>{t('Alıcı')}: {d.recipient}</small>}{d.status==='pending'&&d.next_attempt_at>Math.floor(Date.now()/1000)&&<small>{t('Sıradaki deneme')}: {inZone(d.next_attempt_at,tz)}</small>}{d.media_note&&<small className="media-note">{d.media_note}</small>}{d.error&&<small>{d.error}</small>}{d.error_code&&<small className="error-code">{t('Kod')}: {d.error_code}</small>}{d.retry_count>0&&<small>{t('Otomatik tekrar')}: {d.retry_count}/3</small>}{d.externalId&&<small className="external-id">{t('İşlem')}: {d.externalId}</small>}
{d.attempts.length>0&&<details className="attempts"><summary><History size={13}/>{d.attempts_total??d.attempts.length} {t('deneme')}{(d.attempts_total??0)>d.attempts.length?` · ${t('son')} ${d.attempts.length}`:''}</summary><ol>{d.attempts.map((a:any,i:number)=><li key={i}><span>{inZone(a.started_at,tz,{dateStyle:'short',timeStyle:'medium'})}</span><strong>{t(outcomes[a.outcome]||a.outcome)}</strong><span>{t(stages[a.stage]||a.stage)}</span>{a.error_code&&<code>{a.error_code}</code>}{a.error&&<em>{t(a.error)}</em>}</li>)}</ol></details>}
{d.status==='failed'&&can('approve')&&<button className="secondary" onClick={()=>act('retry',{delivery_id:d.id},t('Yeniden kuyruğa alındı.'))}>{t('Tekrar dene')}</button>}</div>)}</div>}
<div className="post-actions">
{p.status==='pending_approval'&&can('approve')&&<><button className="primary" onClick={()=>act(`posts/${p.id}/approve`,{},t(p.scheduled_at?'Onaylandı, planlanan zamanda gönderilecek.':'Onaylandı, gönderim başladı.'))}><Check size={15}/>{t('Onayla')}</button><button className="secondary" onClick={()=>reject(p)}><X size={15}/>{t('Reddet')}</button></>}
{['draft','rejected','pending_approval'].includes(p.status)&&can('compose')&&<button className="secondary" onClick={()=>onEdit(p)}><Pencil size={14}/>{t('Düzenle')}</button>}
{p.status==='scheduled'&&can('approve')&&<button className="secondary" onClick={()=>confirm(t('Plan iptal edilsin mi? İçerik taslağa döner.'))&&act(`posts/${p.id}/cancel`,{},t('Plan iptal edildi, içerik taslağa döndü.'))}><CalendarClock size={14}/>{t('Planı iptal et')}</button>}
{onDuplicate&&<button className="secondary" title={t('Bu içeriğin kopyasıyla yeni taslak başlat')} onClick={()=>onDuplicate(p)}><Copy size={14}/>{t('Kopyala')}</button>}
{['draft','rejected'].includes(p.status)&&can('compose')&&<button className="text-button" onClick={()=>confirm(t('Bu içerik kalıcı olarak silinsin mi?'))&&act(`posts/${p.id}`,{},t('İçerik silindi.'),'DELETE')}><Trash2 size={14}/>{t('Sil')}</button>}
</div></article>)}</section></>}
