import {useCallback,useEffect,useState} from 'react';
import {Server,Building2,Activity,AlertTriangle,DatabaseBackup,CheckCircle2,XCircle,MinusCircle,Copy,Globe} from 'lucide-react';
import {toast} from 'sonner';
import {api,bytes,platforms,statuses,outcomes,stages} from './api';
import {locale,t} from './i18n';

function Health({label,value,detail}:any){const Icon=value===true?CheckCircle2:value===false?XCircle:MinusCircle;return <div className={'health '+(value===true?'ok':value===false?'bad':'off')}><Icon size={18}/><div><strong>{label}</strong><small>{detail}</small></div></div>}
const date=(value:number)=>value?new Date(value*1000).toLocaleString(locale()):'';

export default function System({settings,refreshState}:any){
const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[secret,setSecret]=useState<any>(null),[publicUrl,setPublicUrl]=useState(settings.public_base_url||'');
const load=useCallback(async()=>{try{setData(await api('system/overview'))}catch(e:any){toast.error(e.message)}},[]);
useEffect(()=>{load();const id=setInterval(()=>{if(!document.hidden)load()},10000);return()=>clearInterval(id)},[load]);
if(!data)return <div className="empty-state">{t('Sistem durumu yükleniyor…')}</div>;
const h=data.health,q=data.queue;
return <div className="system">
<div className="notice"><Server size={18}/><span>{t('Bu ekran şirketlerin içeriklerini ve erişim anahtarlarını göstermez; yalnızca işletim bilgileri (kuyruk, hata kodları, depolama, servis sağlığı) yer alır.')}</span></div>
<section className="panel pad"><h2><Activity size={18}/>{t('Servis sağlığı')}</h2><div className="health-grid"><Health label={t('Veritabanı')} value={h.database} detail={h.database_kind==='postgresql'?'PostgreSQL':h.database_kind==='sqlite'?t('SQLite (yerel)'):h.database_kind}/><Health label={t('Redis / kuyruk')} value={h.redis} detail={h.queue_mode==='celery'?'Celery + Redis':t('Yerel işleyici')}/><Health label={t('Medya depolama')} value={h.storage} detail={data.storage==='cloudinary'?'Cloudinary':t('Sunucu diski')}/></div></section>
<div className="stats">{[{label:'Şimdi gönderilecek',value:q.due_now},{label:'Planlı gönderim',value:q.scheduled},{label:'Takılı gönderim',value:q.stuck_sending},{label:'İşlenen / hatalı medya',value:`${q.media_processing} / ${q.media_failed}`}].map(s=><div className="stat-card" key={s.label}><span>{t(s.label)}</span><strong>{s.value}</strong></div>)}</div>
<section className="panel pad"><h2>{t('Kuyruk durumu')}</h2><div className="chip-row">{Object.entries(q.by_status).map(([k,v]:any)=><span key={k} className="pill">{t(statuses[k]||k)}: {v}</span>)}{!Object.keys(q.by_status).length&&<span className="field-help">{t('Henüz gönderim yok.')}</span>}</div>{Object.keys(data.error_codes).length>0&&<><h3 className="sub">{t('Açık hata kodları')}</h3><div className="chip-row">{Object.entries(data.error_codes).map(([k,v]:any)=><span key={k} className="pill warn-pill"><code>{k}</code> × {v}</span>)}</div></>}</section>
<section className="panel pad"><h2><Building2 size={18}/>{t('Şirketler')}</h2>
{secret&&<div className="secret-card" role="alert"><div><strong>{secret.email} · {t('Geçici parola')}</strong><p>{t('Yalnızca şimdi gösterilir. Şirket yöneticisine güvenli bir kanaldan ilet.')}</p><code>{secret.password}</code></div><button className="secondary" onClick={()=>{navigator.clipboard?.writeText(secret.password);toast.success(t('Kopyalandı.'))}}><Copy size={14}/>{t('Kopyala')}</button><button className="text-button" onClick={()=>setSecret(null)}>{t('Kapat')}</button></div>}
<form className="member-add" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);try{const r=await api('system/companies',{name:f.get('name'),admin_email:f.get('email'),admin_name:f.get('admin'),timezone:f.get('tz')||'Europe/Istanbul'});toast.success(t('Şirket oluşturuldu.'));form.reset();if(r.temporary_password)setSecret({email:r.admin_email,password:r.temporary_password});else toast.info(t('{email} mevcut parolasıyla yeni şirkete erişebilir.',{email:r.admin_email}));load();refreshState()}catch(err:any){toast.error(t(err.message))}}}><input name="name" required placeholder={t('Şirket adı')}/><input name="email" type="email" required placeholder={t('Şirket yöneticisinin e-postası')}/><input name="admin" placeholder={t('Yönetici adı (isteğe bağlı)')}/><input name="tz" placeholder="Europe/Istanbul"/><button className="primary">{t('Şirket oluştur')}</button></form>
<div className="table-wrap"><table className="data-table"><thead><tr><th>{t('Şirket')}</th><th>{t('Ekip')}</th><th>{t('İçerik')}</th><th>{t('30 gün')}</th><th>{t('Depolama')}</th><th>{t('Bağlı kanallar')}</th><th></th></tr></thead><tbody>{data.companies.map((c:any)=><tr key={c.id} className={c.disabled?'muted-row':''}><td><strong>{c.name}</strong><small>{c.timezone} · {date(c.created_at)}</small></td><td>{c.members}</td><td>{c.content_count}{c.pending_approval>0&&<small>{c.pending_approval} {t('onay bekliyor')}</small>}</td><td>{c.deliveries_30d}</td><td>{bytes(c.storage_bytes)}<small>{c.media_count} {t('dosya')}</small></td><td>{c.connections.map((p:string)=>platforms.find(x=>x.id===p)?.symbol).join(' ')||'—'}</td><td><button className="text-button" onClick={async()=>{if(!confirm(c.disabled?t('{company} yeniden açılsın mı?',{company:c.name}):t('{company} askıya alınsın mı? Üyeleri bu çalışma alanına giremez.',{company:c.name})))return;try{await api(`system/companies/${c.id}`,{disabled:!c.disabled},'PATCH');load()}catch(e:any){toast.error(t(e.message))}}}>{t(c.disabled?'Yeniden aç':'Askıya al')}</button></td></tr>)}</tbody></table></div></section>
<section className="panel pad"><h2><AlertTriangle size={18}/>{t('Son hatalar ve tekrarlar')}</h2>{!data.failures.length?<p className="field-help">{t('Kayıtlı hata yok.')}</p>:<div className="table-wrap"><table className="data-table"><thead><tr><th>{t('Zaman')}</th><th>{t('Şirket')}</th><th>{t('Kanal')}</th><th>{t('Sonuç')}</th><th>{t('Aşama')}</th><th>{t('Neden')}</th></tr></thead><tbody>{data.failures.map((f:any,i:number)=><tr key={i}><td>{date(f.at)}</td><td>{f.company}</td><td>{platforms.find(x=>x.id===f.platform)?.name}</td><td>{t(outcomes[f.outcome]||f.outcome)}</td><td>{t(stages[f.stage]||f.stage)}</td><td>{f.error_code&&<code>{f.error_code}</code>}<small>{t(f.error)}</small></td></tr>)}</tbody></table></div>}</section>
<section className="panel pad"><h2><DatabaseBackup size={18}/>{t('Yedekler')}</h2><p className="field-help">{t('Otomatik yedek her gün alınır ve son 14 yedek saklanır. Her yedek, geçici bir veritabanına geri yüklenerek kontrol edilebilir. Yedeklerdeki erişim anahtarları şifrelidir; geri yüklemek için aynı CREDENTIAL_KEY gerekir.')}</p><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await api('system/backup',{});r.verified?toast.success(`${t('Yedek alındı ve geri yükleme kontrolünden geçti')}: ${r.file}`):toast.error(`${t('Yedek alındı ama kontrol başarısız')}: ${JSON.stringify(r.mismatches)}`);load()}catch(e:any){toast.error(t(e.message))}finally{setBusy(false)}}}>{t(busy?'Yedekleniyor…':'Şimdi yedek al ve doğrula')}</button>
{data.backups.length>0&&<div className="table-wrap"><table className="data-table"><thead><tr><th>{t('Dosya')}</th><th>{t('Boyut')}</th><th>{t('Tarih')}</th><th></th></tr></thead><tbody>{data.backups.map((b:any)=><tr key={b.file}><td><code>{b.file}</code></td><td>{bytes(b.size)}</td><td>{date(b.created_at)}</td><td><button className="text-button" onClick={async()=>{try{const r=await api(`system/backup/${b.file}/verify`,{});r.ok?toast.success(t('Geri yükleme kontrolü başarılı. Tablolar ve kayıt sayıları eşleşiyor.')):toast.error(`${t('Uyuşmazlık')}: ${JSON.stringify(r.mismatches)}`)}catch(e:any){toast.error(t(e.message))}}}>{t('Geri yüklemeyi dene')}</button></td></tr>)}</tbody></table></div>}</section>
<section className="panel pad"><h2><Globe size={18}/>{t('Sunucunun herkese açık adresi')}</h2><p className="field-help">{t(data.storage==='cloudinary'?'Medya Cloudinary üzerinden sunulduğu için Instagram bu adrese ihtiyaç duymaz. OAuth dönüşleri ve kendi alan adın için yine de ayarlayabilirsin.':'Instagram görsel ve videoları bu adresten okur. Yerel adresler (localhost) çalışmaz.')}</p><form className="member-add" onSubmit={async e=>{e.preventDefault();try{await api('settings/public',{public_base_url:publicUrl});toast.success(t('Adres kaydedildi.'));refreshState()}catch(err:any){toast.error(t(err.message))}}}><input value={publicUrl} onChange={e=>setPublicUrl(e.target.value)} placeholder="https://akis.example.com"/><button className="primary">{t('Kaydet')}</button></form></section>
</div>}
