import {useCallback,useEffect,useState} from 'react';
import {Server,Building2,Activity,AlertTriangle,DatabaseBackup,CheckCircle2,XCircle,MinusCircle,Copy,Globe} from 'lucide-react';
import {toast} from 'sonner';
import {api,bytes,platforms,statuses,outcomes,stages} from './api';

function Health({label,value,detail}:any){const Icon=value===true?CheckCircle2:value===false?XCircle:MinusCircle;return <div className={'health '+(value===true?'ok':value===false?'bad':'off')}><Icon size={18}/><div><strong>{label}</strong><small>{detail}</small></div></div>}
const date=(t:number)=>t?new Date(t*1000).toLocaleString('tr-TR'):'';

export default function System({settings,refreshState}:any){
const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[secret,setSecret]=useState<any>(null),[publicUrl,setPublicUrl]=useState(settings.public_base_url||'');
const load=useCallback(async()=>{try{setData(await api('system/overview'))}catch(e:any){toast.error(e.message)}},[]);
useEffect(()=>{load();const id=setInterval(()=>{if(!document.hidden)load()},10000);return()=>clearInterval(id)},[load]);
if(!data)return <div className="empty-state">Sistem durumu yükleniyor…</div>;
const h=data.health,q=data.queue;
return <div className="system">
<div className="notice"><Server size={18}/><span>Bu ekran şirketlerin içeriklerini ve erişim anahtarlarını göstermez; yalnızca işletim bilgileri (kuyruk, hata kodları, depolama, servis sağlığı) yer alır.</span></div>
<section className="panel pad"><h2><Activity size={18}/>Servis sağlığı</h2><div className="health-grid"><Health label="Veritabanı" value={h.database} detail={h.database_kind==='postgresql'?'PostgreSQL':h.database_kind==='sqlite'?'SQLite (yerel)':h.database_kind}/><Health label="Redis / kuyruk" value={h.redis} detail={h.queue_mode==='celery'?'Celery + Redis':'Yerel işleyici'}/><Health label="Medya depolama" value={h.storage} detail={data.storage==='cloudinary'?'Cloudinary':'Sunucu diski'}/></div></section>
<div className="stats">{[{label:'Şimdi gönderilecek',value:q.due_now},{label:'Planlı gönderim',value:q.scheduled},{label:'Takılı gönderim',value:q.stuck_sending},{label:'İşlenen / hatalı medya',value:`${q.media_processing} / ${q.media_failed}`}].map(s=><div className="stat-card" key={s.label}><span>{s.label}</span><strong>{s.value}</strong></div>)}</div>
<section className="panel pad"><h2>Kuyruk durumu</h2><div className="chip-row">{Object.entries(q.by_status).map(([k,v]:any)=><span key={k} className="pill">{statuses[k]||k}: {v}</span>)}{!Object.keys(q.by_status).length&&<span className="field-help">Henüz gönderim yok.</span>}</div>{Object.keys(data.error_codes).length>0&&<><h3 className="sub">Açık hata kodları</h3><div className="chip-row">{Object.entries(data.error_codes).map(([k,v]:any)=><span key={k} className="pill warn-pill"><code>{k}</code> × {v}</span>)}</div></>}</section>
<section className="panel pad"><h2><Building2 size={18}/>Şirketler</h2>
{secret&&<div className="secret-card" role="alert"><div><strong>{secret.email} için geçici parola</strong><p>Yalnızca şimdi gösterilir. Şirket yöneticisine güvenli bir kanaldan ilet.</p><code>{secret.password}</code></div><button className="secondary" onClick={()=>{navigator.clipboard?.writeText(secret.password);toast.success('Kopyalandı.')}}><Copy size={14}/>Kopyala</button><button className="text-button" onClick={()=>setSecret(null)}>Kapat</button></div>}
<form className="member-add" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);try{const r=await api('system/companies',{name:f.get('name'),admin_email:f.get('email'),admin_name:f.get('admin'),timezone:f.get('tz')||'Europe/Istanbul'});toast.success('Şirket oluşturuldu.');form.reset();if(r.temporary_password)setSecret({email:r.admin_email,password:r.temporary_password});else toast.info(`${r.admin_email} mevcut parolasıyla yeni şirkete erişebilir.`);load();refreshState()}catch(err:any){toast.error(err.message)}}}><input name="name" required placeholder="Şirket adı"/><input name="email" type="email" required placeholder="Şirket yöneticisinin e-postası"/><input name="admin" placeholder="Yönetici adı (isteğe bağlı)"/><input name="tz" placeholder="Europe/Istanbul"/><button className="primary">Şirket oluştur</button></form>
<div className="table-wrap"><table className="data-table"><thead><tr><th>Şirket</th><th>Ekip</th><th>İçerik</th><th>30 gün</th><th>Depolama</th><th>Bağlı kanallar</th><th></th></tr></thead><tbody>{data.companies.map((c:any)=><tr key={c.id} className={c.disabled?'muted-row':''}><td><strong>{c.name}</strong><small>{c.timezone} · {date(c.created_at)}</small></td><td>{c.members}</td><td>{c.content_count}{c.pending_approval>0&&<small>{c.pending_approval} onay bekliyor</small>}</td><td>{c.deliveries_30d}</td><td>{bytes(c.storage_bytes)}<small>{c.media_count} dosya</small></td><td>{c.connections.map((p:string)=>platforms.find(x=>x.id===p)?.symbol).join(' ')||'—'}</td><td><button className="text-button" onClick={async()=>{if(!confirm(c.disabled?`${c.name} yeniden açılsın mı?`:`${c.name} askıya alınsın mı? Üyeleri bu çalışma alanına giremez.`))return;try{await api(`system/companies/${c.id}`,{disabled:!c.disabled},'PATCH');load()}catch(e:any){toast.error(e.message)}}}>{c.disabled?'Yeniden aç':'Askıya al'}</button></td></tr>)}</tbody></table></div></section>
<section className="panel pad"><h2><AlertTriangle size={18}/>Son hatalar ve tekrarlar</h2>{!data.failures.length?<p className="field-help">Kayıtlı hata yok.</p>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Zaman</th><th>Şirket</th><th>Kanal</th><th>Sonuç</th><th>Aşama</th><th>Neden</th></tr></thead><tbody>{data.failures.map((f:any,i:number)=><tr key={i}><td>{date(f.at)}</td><td>{f.company}</td><td>{platforms.find(x=>x.id===f.platform)?.name}</td><td>{outcomes[f.outcome]||f.outcome}</td><td>{stages[f.stage]||f.stage}</td><td>{f.error_code&&<code>{f.error_code}</code>}<small>{f.error}</small></td></tr>)}</tbody></table></div>}</section>
<section className="panel pad"><h2><DatabaseBackup size={18}/>Yedekler</h2><p className="field-help">Otomatik yedek her gün alınır ve son {14} yedek saklanır. Her yedek, geçici bir veritabanına geri yüklenerek kontrol edilebilir. Yedeklerdeki erişim anahtarları şifrelidir; geri yüklemek için aynı CREDENTIAL_KEY gerekir.</p><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await api('system/backup',{});r.verified?toast.success(`Yedek alındı ve geri yükleme kontrolünden geçti: ${r.file}`):toast.error('Yedek alındı ama kontrol başarısız: '+JSON.stringify(r.mismatches));load()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}}>{busy?'Yedekleniyor…':'Şimdi yedek al ve doğrula'}</button>
{data.backups.length>0&&<div className="table-wrap"><table className="data-table"><thead><tr><th>Dosya</th><th>Boyut</th><th>Tarih</th><th></th></tr></thead><tbody>{data.backups.map((b:any)=><tr key={b.file}><td><code>{b.file}</code></td><td>{bytes(b.size)}</td><td>{date(b.created_at)}</td><td><button className="text-button" onClick={async()=>{try{const r=await api(`system/backup/${b.file}/verify`,{});r.ok?toast.success('Geri yükleme kontrolü başarılı. Tablolar ve kayıt sayıları eşleşiyor.'):toast.error('Uyuşmazlık: '+JSON.stringify(r.mismatches))}catch(e:any){toast.error(e.message)}}}>Geri yüklemeyi dene</button></td></tr>)}</tbody></table></div>}</section>
<section className="panel pad"><h2><Globe size={18}/>Sunucunun herkese açık adresi</h2><p className="field-help">{data.storage==='cloudinary'?'Medya Cloudinary üzerinden sunulduğu için Instagram bu adrese ihtiyaç duymaz. OAuth dönüşleri ve kendi alan adın için yine de ayarlayabilirsin.':'Instagram görsel ve videoları bu adresten okur. Yerel adresler (localhost) çalışmaz.'}</p><form className="member-add" onSubmit={async e=>{e.preventDefault();try{await api('settings/public',{public_base_url:publicUrl});toast.success('Adres kaydedildi.');refreshState()}catch(err:any){toast.error(err.message)}}}><input value={publicUrl} onChange={e=>setPublicUrl(e.target.value)} placeholder="https://akis.ornek.com"/><button className="primary">Kaydet</button></form></section>
</div>}
