import {useCallback,useEffect,useState} from 'react';
import {Users,ShieldCheck,KeyRound,Trash2,History,Building2,Copy} from 'lucide-react';
import {toast} from 'sonner';
import {api,roleNames,bytes,inZone,platforms,isApp,serverUrl} from './api';
import {locale,t} from './i18n';

const actionNames:Record<string,string>={'user.login':'Giriş yaptı','user.password_changed':'Parolasını değiştirdi','user.2fa_enabled':'İki aşamalı girişi açtı','user.2fa_disabled':'İki aşamalı girişi kapattı','connection.saved':'Hesap bağlantısını kaydetti','connection.oauth':'Hesap bağladı','connection.removed':'Hesap bağlantısını kaldırdı','settings.oauth_app':'Uygulama ayarını değiştirdi','content.draft_saved':'Taslak kaydetti','content.submitted':'Onaya gönderdi','content.approved':'Onayladı','content.rejected':'Reddetti','content.edited':'İçeriği düzenledi','content.deleted':'İçeriği sildi','content.schedule_cancelled':'Planı iptal etti','delivery.retried':'Gönderimi yeniden denedi','media.uploaded':'Medya yükledi','media.updated':'Medyayı düzenledi','media.deleted':'Medyayı sildi','member.added':'Ekibe üye ekledi','member.role_changed':'Rol değiştirdi','member.removed':'Üyeyi çıkardı','member.password_reset':'Üye parolasını sıfırladı','member.invited':'Ekibe davet etti','member.joined':'Daveti kabul edip ekibe katıldı','member.invite_revoked':'Daveti iptal etti','user.sessions_revoked':'Diğer oturumlarını kapattı','company.updated':'Şirket ayarlarını değiştirdi','system.company_created':'Şirketi oluşturdu','system.bootstrap':'Sistem kurulumu'};
function describe(d:any){const parts=[];if(d.platform)parts.push(platforms.find(p=>p.id===d.platform)?.name||d.platform);if(d.platforms)parts.push(d.platforms.map((x:string)=>platforms.find(p=>p.id===x)?.name||x).join(', '));if(d.account)parts.push(d.account);if(d.email)parts.push(d.email);if(d.role)parts.push(t(roleNames[d.role]));if(d.old&&d.new)parts.push(`${t(roleNames[d.old])} → ${t(roleNames[d.new])}`);if(d.filename)parts.push(d.filename);if(d.note)parts.push(`“${d.note}”`);if(d.timezone)parts.push(d.timezone);if(d.require_approval!==undefined)parts.push(t(d.require_approval?'Onay zorunlu':'Onay gerekmez'));return parts.join(' · ')}

function InviteLink({email,url,expires,onClose}:any){return <div className="secret-card" role="alert"><KeyRound size={18}/><div><strong>{email} · {t('Davet bağlantısı')}</strong><p>{t('Bağlantı yalnızca şimdi gösterilir ve')} {new Date(expires*1000).toLocaleDateString(locale())} {t('tarihine kadar bir kez kullanılabilir. Kişiye güvenli bir kanaldan ilet; hesabı varsa kendi parolasıyla, yoksa kendi belirlediği parolayla katılır.')}</p><code>{url}</code></div><button className="secondary" onClick={()=>{navigator.clipboard?.writeText(url);toast.success(t('Kopyalandı.'))}}><Copy size={14}/>{t('Kopyala')}</button><button className="text-button" onClick={onClose}>{t('Kapat')}</button></div>}

function Secret({email,password,onClose}:any){return <div className="secret-card" role="alert"><KeyRound size={18}/><div><strong>{email} · {t('Geçici parola')}</strong><p>{t('Bu parola yalnızca şimdi gösterilir. Kişiye güvenli bir kanaldan ilet; ilk girişte değiştirmesi istenir.')}</p><code>{password}</code></div><button className="secondary" onClick={()=>{navigator.clipboard?.writeText(password);toast.success(t('Kopyalandı.'))}}><Copy size={14}/>{t('Kopyala')}</button><button className="text-button" onClick={onClose}>{t('Kapat')}</button></div>}

export default function Team({tz,can,me,refreshState}:any){
const [link,setLink]=useState<any>(null),[data,setData]=useState<any>(null),[audit,setAudit]=useState<any[]>([]),[more,setMore]=useState(true),[secret,setSecret]=useState<any>(null),[email,setEmail]=useState(''),[name,setName]=useState(''),[role,setRole]=useState('editor');
const load=useCallback(async()=>{try{setData(await api('company'))}catch(e:any){toast.error(e.message)}},[]);
const loadAudit=useCallback(async(before=0,beforeId='')=>{try{const r=await api('audit?'+new URLSearchParams({before:String(before),before_id:beforeId,limit:'50'}));setAudit(a=>before?[...a,...r.items]:r.items);setMore(r.items.length===50)}catch(e:any){toast.error(e.message)}},[]);
useEffect(()=>{load();loadAudit()},[load,loadAudit]);
async function call(path:string,body:any,method:string|undefined,msg:string){try{const r=await api(path,body,method);toast.success(msg);load();loadAudit();refreshState();return r}catch(e:any){toast.error(e.message)}}
if(!data)return <div className="empty-state">{t('Şirket bilgileri yükleniyor…')}</div>;
const c=data.company,u=data.usage;
const zones:string[]=(Intl as any).supportedValuesOf?.('timeZone')||[c.timezone];
return <div className="team">
<div className="stats">{[{label:'Ekip üyesi',value:data.members.length},{label:'Son 30 gün gönderim',value:u.deliveries_30d},{label:'Onay bekleyen',value:u.pending_approval},{label:'Medya depolama',value:bytes(u.storage_bytes)}].map(s=><div className="stat-card" key={s.label}><span>{t(s.label)}</span><strong>{s.value}</strong></div>)}</div>
{can('settings')&&<section className="panel pad"><h2><Building2 size={18}/>{t('Şirket ayarları')}</h2><form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);call('company',{name:f.get('name'),timezone:f.get('timezone'),require_approval:f.get('approval')==='on'},'PATCH',t('Şirket ayarları kaydedildi.'))}}><label>{t('Şirket adı')}<input name="name" defaultValue={c.name} required maxLength={120}/></label><label>{t('Saat dilimi')}<select name="timezone" defaultValue={c.timezone}>{zones.map(z=><option key={z}>{z}</option>)}</select></label><label className="inline-options wide"><input type="checkbox" name="approval" defaultChecked={c.require_approval}/>{t('Editörlerin hazırladığı içerikler yayımlanmadan önce onaylansın')}</label><p className="field-help wide">{t('Takvim ve planlı paylaşımlar bu saat dilimine göre çalışır. Yöneticiler ve onaylayanlar kendi içeriklerini doğrudan yayımlayabilir.')}</p><button className="primary">{t('Kaydet')}</button></form></section>}
<section className="panel pad"><h2><Users size={18}/>{t('Ekip ve roller')}</h2>
<div className="role-help">{Object.entries({admin:'Ekibi, bağlı hesapları, ayarları ve işlem geçmişini yönetir.',approver:'İçerik hazırlar; editörlerin içeriklerini onaylar veya reddeder.',editor:'İçerik ve medya hazırlar, onaya gönderir.',viewer:'Yalnızca içerikleri ve sonuçları görüntüler.'}).map(([k,v])=><div key={k}><strong>{t(roleNames[k])}</strong><span>{t(v)}</span></div>)}</div>
{secret&&<Secret {...secret} onClose={()=>setSecret(null)}/>}{link&&<InviteLink {...link} onClose={()=>setLink(null)}/>}
<form className="member-add" onSubmit={async e=>{e.preventDefault();const r=await call('company/members',{email,name,role},undefined,t('Davet oluşturuldu.'));if(r){setEmail('');setName('');setLink({email:r.email,url:(isApp?serverUrl():location.origin)+r.invite_path,expires:r.expires_at})}}}><input type="email" required placeholder={t('E-posta')} value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder={t('Ad Soyad (isteğe bağlı)')} value={name} onChange={e=>setName(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value)} aria-label={t('Rol')}>{Object.entries(roleNames).map(([k,v])=><option key={k} value={k}>{t(v)}</option>)}</select><button className="primary">{t('Davet et')}</button></form>
{data.invites?.length>0&&<><h3 className="sub">{t('Bekleyen davetler')}</h3><div className="table-wrap"><table className="data-table"><thead><tr><th>{t('E-posta')}</th><th>{t('Rol')}</th><th>{t('Son geçerlilik')}</th><th></th></tr></thead><tbody>{data.invites.map((i:any)=><tr key={i.id}><td>{i.email}</td><td>{t(i.role_name)}</td><td>{inZone(i.expires_at,tz,{dateStyle:'medium'})}</td><td className="row-actions"><button className="text-button" onClick={()=>confirm(t('{email} davetinin bağlantısı iptal edilsin mi?',{email:i.email}))&&call(`company/invites/${i.id}`,{},'DELETE',t('Davet iptal edildi.'))}>{t('İptal et')}</button></td></tr>)}</tbody></table></div></>}
<div className="table-wrap"><table className="data-table"><thead><tr><th>{t('Kişi')}</th><th>{t('Rol')}</th><th>{t('Güvenlik')}</th><th></th></tr></thead><tbody>{data.members.map((m:any)=><tr key={m.user_id}><td><strong>{m.name||m.email}</strong><small>{m.email}</small></td><td><select value={m.role} aria-label={`${m.email} ${t('Rol')}`} onChange={e=>call(`company/members/${m.user_id}`,{role:e.target.value},'PATCH',t('Rol güncellendi.'))}>{Object.entries(roleNames).map(([k,v])=><option key={k} value={k}>{t(v)}</option>)}</select></td><td>{m.totp_enabled?<span className="pill saved"><ShieldCheck size={12}/>{t('2FA açık')}</span>:<span className="pill status-off">{t('2FA kapalı')}</span>}{m.must_change_password&&<small>{t('İlk girişi bekliyor')}</small>}</td><td className="row-actions">{m.user_id!==me.id&&<><button className="icon-button" title={t('Geçici parola oluştur')} aria-label={t('Parolayı sıfırla')} onClick={async()=>{if(!confirm(t('{email} için yeni geçici parola oluşturulsun mu? Mevcut oturumları kapanır.',{email:m.email})))return;const r=await call(`company/members/${m.user_id}/reset-password`,{},undefined,t('Parola sıfırlandı.'));if(r)setSecret({email:m.email,password:r.temporary_password})}}><KeyRound size={15}/></button><button className="icon-button" title={t('Ekipten çıkar')} aria-label={t('Ekipten çıkar')} onClick={()=>confirm(t('{email} ekipten çıkarılsın mı?',{email:m.email}))&&call(`company/members/${m.user_id}`,{},'DELETE',t('Üye çıkarıldı.'))}><Trash2 size={15}/></button></>}</td></tr>)}</tbody></table></div></section>
{can('audit')&&<section className="panel pad"><h2><History size={18}/>{t('İşlem geçmişi')}</h2><p className="field-help">{t('Kim içeriği değiştirdi, kim onayladı, kim hangi hesabı bağladı. Erişim anahtarları bu kayıtlara hiçbir zaman yazılmaz.')}</p><ol className="audit-list">{audit.map(a=><li key={a.id}><span className="audit-time">{inZone(a.at,tz,{dateStyle:'short',timeStyle:'short'})}</span><strong>{a.user||t('Sistem')}</strong><span>{t(actionNames[a.action]||a.action)}</span><small>{describe(a.details)}</small></li>)}</ol>{more&&audit.length>0&&<button className="secondary" onClick={()=>loadAudit(audit[audit.length-1].at,audit[audit.length-1].id)}>{t('Daha eski kayıtlar')}</button>}</section>}
</div>}
