import {useCallback,useEffect,useState} from 'react';
import {Users,ShieldCheck,KeyRound,Trash2,History,Building2,Copy} from 'lucide-react';
import {toast} from 'sonner';
import {api,roleNames,bytes,inZone,platforms} from './api';

const actionNames:Record<string,string>={'user.login':'Giriş yaptı','user.password_changed':'Parolasını değiştirdi','user.2fa_enabled':'İki aşamalı girişi açtı','user.2fa_disabled':'İki aşamalı girişi kapattı','connection.saved':'Hesap bağlantısını kaydetti','connection.oauth':'Hesap bağladı','connection.removed':'Hesap bağlantısını kaldırdı','settings.oauth_app':'Uygulama ayarını değiştirdi','content.draft_saved':'Taslak kaydetti','content.submitted':'Onaya gönderdi','content.approved':'Onayladı','content.rejected':'Reddetti','content.edited':'İçeriği düzenledi','content.deleted':'İçeriği sildi','content.schedule_cancelled':'Planı iptal etti','delivery.retried':'Gönderimi yeniden denedi','media.uploaded':'Medya yükledi','media.updated':'Medyayı düzenledi','media.deleted':'Medyayı sildi','member.added':'Ekibe üye ekledi','member.role_changed':'Rol değiştirdi','member.removed':'Üyeyi çıkardı','member.password_reset':'Üye parolasını sıfırladı','company.updated':'Şirket ayarlarını değiştirdi','system.company_created':'Şirketi oluşturdu','system.bootstrap':'Sistem kurulumu'};
function describe(d:any){const parts=[];if(d.platform)parts.push(platforms.find(p=>p.id===d.platform)?.name||d.platform);if(d.platforms)parts.push(d.platforms.map((x:string)=>platforms.find(p=>p.id===x)?.name||x).join(', '));if(d.account)parts.push(d.account);if(d.email)parts.push(d.email);if(d.role)parts.push(roleNames[d.role]);if(d.old&&d.new)parts.push(`${roleNames[d.old]} → ${roleNames[d.new]}`);if(d.filename)parts.push(d.filename);if(d.note)parts.push(`“${d.note}”`);if(d.timezone)parts.push(d.timezone);if(d.require_approval!==undefined)parts.push(d.require_approval?'Onay zorunlu':'Onay gerekmez');return parts.join(' · ')}

function Secret({email,password,onClose}:any){return <div className="secret-card" role="alert"><KeyRound size={18}/><div><strong>{email} için geçici parola</strong><p>Bu parola yalnızca şimdi gösterilir. Kişiye güvenli bir kanaldan ilet; ilk girişte değiştirmesi istenir.</p><code>{password}</code></div><button className="secondary" onClick={()=>{navigator.clipboard?.writeText(password);toast.success('Kopyalandı.')}}><Copy size={14}/>Kopyala</button><button className="text-button" onClick={onClose}>Kapat</button></div>}

export default function Team({tz,can,me,refreshState}:any){
const [data,setData]=useState<any>(null),[audit,setAudit]=useState<any[]>([]),[more,setMore]=useState(true),[secret,setSecret]=useState<any>(null),[email,setEmail]=useState(''),[name,setName]=useState(''),[role,setRole]=useState('editor');
const load=useCallback(async()=>{try{setData(await api('company'))}catch(e:any){toast.error(e.message)}},[]);
const loadAudit=useCallback(async(before=0)=>{try{const r=await api('audit?'+new URLSearchParams({before:String(before),limit:'50'}));setAudit(a=>before?[...a,...r.items]:r.items);setMore(r.items.length===50)}catch(e:any){toast.error(e.message)}},[]);
useEffect(()=>{load();loadAudit()},[load,loadAudit]);
async function call(path:string,body:any,method:string|undefined,msg:string){try{const r=await api(path,body,method);toast.success(msg);load();loadAudit();refreshState();return r}catch(e:any){toast.error(e.message)}}
if(!data)return <div className="empty-state">Şirket bilgileri yükleniyor…</div>;
const c=data.company,u=data.usage;
const zones:string[]=(Intl as any).supportedValuesOf?.('timeZone')||[c.timezone];
return <div className="team">
<div className="stats">{[{label:'Ekip üyesi',value:data.members.length},{label:'Son 30 gün gönderim',value:u.deliveries_30d},{label:'Onay bekleyen',value:u.pending_approval},{label:'Medya depolama',value:bytes(u.storage_bytes)}].map(s=><div className="stat-card" key={s.label}><span>{s.label}</span><strong>{s.value}</strong></div>)}</div>
{can('settings')&&<section className="panel pad"><h2><Building2 size={18}/>Şirket ayarları</h2><form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);call('company',{name:f.get('name'),timezone:f.get('timezone'),require_approval:f.get('approval')==='on'},'PATCH','Şirket ayarları kaydedildi.')}}><label>Şirket adı<input name="name" defaultValue={c.name} required maxLength={120}/></label><label>Saat dilimi<select name="timezone" defaultValue={c.timezone}>{zones.map(z=><option key={z}>{z}</option>)}</select></label><label className="inline-options wide"><input type="checkbox" name="approval" defaultChecked={c.require_approval}/>Editörlerin hazırladığı içerikler yayımlanmadan önce onaylansın</label><p className="field-help wide">Takvim ve planlı paylaşımlar bu saat dilimine göre çalışır. Yöneticiler ve onaylayanlar kendi içeriklerini doğrudan yayımlayabilir.</p><button className="primary">Kaydet</button></form></section>}
<section className="panel pad"><h2><Users size={18}/>Ekip ve roller</h2>
<div className="role-help">{Object.entries({admin:'Ekibi, bağlı hesapları, ayarları ve işlem geçmişini yönetir.',approver:'İçerik hazırlar; editörlerin içeriklerini onaylar veya reddeder.',editor:'İçerik ve medya hazırlar, onaya gönderir.',viewer:'Yalnızca içerikleri ve sonuçları görüntüler.'}).map(([k,v])=><div key={k}><strong>{roleNames[k]}</strong><span>{v}</span></div>)}</div>
{secret&&<Secret {...secret} onClose={()=>setSecret(null)}/>}
<form className="member-add" onSubmit={async e=>{e.preventDefault();const r=await call('company/members',{email,name,role},undefined,'Üye eklendi.');if(r){setEmail('');setName('');if(r.temporary_password)setSecret({email:r.email,password:r.temporary_password})}}}><input type="email" required placeholder="E-posta" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Ad Soyad (isteğe bağlı)" value={name} onChange={e=>setName(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value)} aria-label="Rol">{Object.entries(roleNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button className="primary">Ekibe ekle</button></form>
<div className="table-wrap"><table className="data-table"><thead><tr><th>Kişi</th><th>Rol</th><th>Güvenlik</th><th></th></tr></thead><tbody>{data.members.map((m:any)=><tr key={m.user_id}><td><strong>{m.name||m.email}</strong><small>{m.email}</small></td><td><select value={m.role} aria-label={`${m.email} rolü`} onChange={e=>call(`company/members/${m.user_id}`,{role:e.target.value},'PATCH','Rol güncellendi.')}>{Object.entries(roleNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></td><td>{m.totp_enabled?<span className="pill saved"><ShieldCheck size={12}/>2FA açık</span>:<span className="pill">2FA kapalı</span>}{m.must_change_password&&<small>İlk girişi bekliyor</small>}</td><td className="row-actions">{m.user_id!==me.id&&<><button className="icon-button" title="Geçici parola oluştur" aria-label="Parolayı sıfırla" onClick={async()=>{if(!confirm(`${m.email} için yeni geçici parola oluşturulsun mu? Mevcut oturumları kapanır.`))return;const r=await call(`company/members/${m.user_id}/reset-password`,{},undefined,'Parola sıfırlandı.');if(r)setSecret({email:m.email,password:r.temporary_password})}}><KeyRound size={15}/></button><button className="icon-button" title="Ekipten çıkar" aria-label="Ekipten çıkar" onClick={()=>confirm(`${m.email} ekipten çıkarılsın mı?`)&&call(`company/members/${m.user_id}`,{},'DELETE','Üye çıkarıldı.')}><Trash2 size={15}/></button></>}</td></tr>)}</tbody></table></div></section>
{can('audit')&&<section className="panel pad"><h2><History size={18}/>İşlem geçmişi</h2><p className="field-help">Kim içeriği değiştirdi, kim onayladı, kim hangi hesabı bağladı. Erişim anahtarları bu kayıtlara hiçbir zaman yazılmaz.</p><ol className="audit-list">{audit.map(a=><li key={a.id}><span className="audit-time">{inZone(a.at,tz,{dateStyle:'short',timeStyle:'short'})}</span><strong>{a.user||'Sistem'}</strong><span>{actionNames[a.action]||a.action}</span><small>{describe(a.details)}</small></li>)}</ol>{more&&audit.length>0&&<button className="secondary" onClick={()=>loadAudit(audit[audit.length-1].at)}>Daha eski kayıtlar</button>}</section>}
</div>}
