import React from 'react';
import {createRoot} from 'react-dom/client';
import Home from './page';
import './globals.css';
import './studio/studio.css';
import './studio/theme-dark.css';
import './studio/design.css';
import {applyTheme} from './studio/theme';
import {applyLanguage} from './studio/i18n';
applyTheme();
applyLanguage();
import {registerServiceWorker} from './studio/InstallHint';
registerServiceWorker();
createRoot(document.getElementById('root')!).render(<Home/>);
