import {lazy,Suspense,useEffect,useState,useRef,useCallback} from 'react';
import {Send,Layers3,Link2,FileText,Plus,Check,ShieldCheck,Radio,Loader2,Settings2,RefreshCw,CalendarDays,Images,Users,Server,UserRound,LogOut,CalendarClock,X} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarInset,SidebarTrigger} from '@/components/ui/sidebar';
import SidebarMenuButton from './studio/NavigationButton';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {Toaster,toast} from 'sonner';
import {api,platforms,setCompany,roleNames,zoneInput,inZone,mediaSrc,setToken,isApp,serverUrl,fetchState,forgetState,readHourFormat,saveHourFormat,HourFormat} from './studio/api';
import MediaUpload from './studio/MediaUpload';
import Login from './studio/Login';
import {ThemeSwitch} from './studio/theme';
import InstallHint from './studio/InstallHint';
import Invite,{inviteToken} from './studio/Invite';
import {Language,readLanguage,saveLanguage,t} from './studio/i18n';
const Posts=lazy(()=>import('./studio/Posts'));
const Calendar=lazy(()=>import('./studio/Calendar'));
const Library=lazy(()=>import('./studio/Library'));
const Connections=lazy(()=>import('./studio/Connections'));
const Settings=lazy(()=>import('./studio/Settings'));
const Team=lazy(()=>import('./studio/Team'));
const System=lazy(()=>import('./studio/System'));
const Account=lazy(()=>import('./studio/Account'));
const empty={company:null,me:{role:null,permissions:[]},connections:[],posts:[],assets:[],settings:{oauth_apps:[],queue:'',app_origin:location.origin,max_upload_mb:100}};
export default function Home(){
const [view,setView]=useState('compose'),[text,setText]=useState(''),[selected,setSelected]=useState<string[]>(['x']),[preview,setPreview]=useState('x'),[state,setState]=useState<any>(empty),[assetId,setAssetId]=useState<string|null>(null),[uploaded,setUploaded]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[recipients,setRecipients]=useState(''),[template,setTemplate]=useState(''),[language,setLanguage]=useState('tr'),[params,setParams]=useState(''),[waMode,setWaMode]=useState('template'),[sessionConfirmed,setSessionConfirmed]=useState(false),[session,setSession]=useState<any>(null),[editing,setEditing]=useState<string|null>(null),[schedule,setSchedule]=useState(''),[picking,setPicking]=useState(false),[postFilter,setPostFilter]=useState('all'),[refreshing,setRefreshing]=useState(false),[lastSynced,setLastSynced]=useState<number|null>(null),[online,setOnline]=useState(()=>navigator.onLine);
const [hourFormat,setHourFormat]=useState<HourFormat>(readHourFormat);
const [uiLanguage,setUiLanguage]=useState<Language>(readLanguage);
const request=useRef({fingerprint:'',id:''});
const refreshInFlight=useRef(false);
const refreshQueued=useRef(false),refreshContext=useRef(0);
const [invite,setInvite]=useState(inviteToken);
useEffect(()=>{const on=()=>setInvite(inviteToken());window.addEventListener('hashchange',on);return()=>window.removeEventListener('hashchange',on)},[]);
const refresh=useCallback(async()=>{if(refreshInFlight.current){refreshQueued.current=true;return}const context=refreshContext.current;refreshInFlight.current=true;setRefreshing(true);try{const j=await fetchState();if(context===refreshContext.current){if(j)setState(j);setError('');setLastSynced(Date.now())}}catch(e:any){if(context===refreshContext.current)setError(e.message)}finally{refreshInFlight.current=false;setRefreshing(false);setLoading(false);if(refreshQueued.current){refreshQueued.current=false;queueMicrotask(refresh)}}},[]);
const loadSession=useCallback(async()=>{forgetState();if(isApp&&!serverUrl()){setSession({authenticated:false});setLoading(false);return}try{const s=await api('session');const companies=s.user?.companies||[];const saved=(()=>{try{return localStorage.getItem('akis-company')}catch{return null}})();const active=companies.find((c:any)=>c.id===saved)||companies[0];if(active)setCompany(active.id);setSession(s);if(s.authenticated&&active)await refresh();else setLoading(false);if(s.user?.must_change_password)setView('account');else if(s.authenticated&&!active&&s.user?.is_system_admin)setView('system')}catch(e:any){setError(e.message);setLoading(false)}},[refresh]);
useEffect(()=>{loadSession()},[loadSession]);
useEffect(()=>{const connected=()=>{setOnline(true);if(session?.authenticated)refresh()},disconnected=()=>setOnline(false),visible=()=>{if(!document.hidden&&navigator.onLine&&session?.authenticated)refresh()};window.addEventListener('online',connected);window.addEventListener('offline',disconnected);document.addEventListener('visibilitychange',visible);return()=>{window.removeEventListener('online',connected);window.removeEventListener('offline',disconnected);document.removeEventListener('visibilitychange',visible)}},[session?.authenticated,refresh]);
useEffect(()=>{if(!session?.authenticated)return;const id=setInterval(()=>{if(!document.hidden&&navigator.onLine)refresh()},4000);return()=>clearInterval(id)},[session?.authenticated,refresh]);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();try{Promise.resolve(context.registerTool({name:'stage_content',description:'Prepare text in the content editor without saving or publishing.',inputSchema:{type:'object',properties:{text:{type:'string',maxLength:5000}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input:any){if(typeof input?.text!=='string'||input.text.length>5000)throw Error(t('Geçersiz metin'));setText(input.text);setView('compose');return {staged:true,published:false}}},{signal:life.signal})).catch(()=>{})}catch{}return()=>life.abort()},[]);
// One unsent draft per person and company; removed on sign-out so a shared computer does not show it to the next user.
const draftKey=state.company?.id&&session?.user?.id?`akis-draft:${session.user.id}:${state.company.id}`:'';
useEffect(()=>{if(!draftKey||editing)return;try{const saved=localStorage.getItem(draftKey);if(saved&&!text){setText(saved);toast.info(t('Kaydedilmemiş metnin geri yüklendi.'))}}catch{}},[draftKey,editing]);
useEffect(()=>{if(!draftKey||editing)return;const id=setTimeout(()=>{try{text.trim()?localStorage.setItem(draftKey,text):localStorage.removeItem(draftKey)}catch{}},400);return()=>clearTimeout(id)},[text,draftKey,editing]);
const perms:string[]=state.me?.permissions||[];const can=useCallback((p:string)=>perms.includes(p),[perms.join()]);
const tz=state.company?.timezone||'Europe/Istanbul';
const asset=state.assets.find((a:any)=>a.id===assetId)||(uploaded?.id===assetId?uploaded:null);
const direct=can('approve')||state.company?.require_approval===false;
function reset(keepStored=false){request.current={fingerprint:'',id:''};try{if(draftKey&&!editing&&!keepStored)localStorage.removeItem(draftKey)}catch{};setText('');setAssetId(null);setUploaded(null);setEditing(null);setSchedule('')}
async function save(send:boolean){setBusy(true);const body={text,platforms:selected,asset_id:assetId,send,scheduled_local:schedule,recipients:recipients.split(/[\s,;]+/).filter(Boolean),template,language,template_params:params.split('\n').filter(Boolean),wa_mode:waMode,session_confirmed:sessionConfirmed};const fingerprint=JSON.stringify(body);if(request.current.fingerprint!==fingerprint)request.current={fingerprint,id:crypto.randomUUID()};try{const r=editing?await api('posts/'+editing,body,'PUT'):await api('posts',{...body,requestId:request.current.id});const outcome=r.outcome||(send?'approved':'draft');toast.success(t(outcome==='submitted'?'Onaya gönderildi. Yetkili onayladığında yayımlanacak.':outcome==='approved'?(schedule?'Planlandı. Belirlenen zamanda gönderilecek.':'Gönderim kuyruğuna eklendi. Akış arka planda devam ediyor.'):'Taslak kaydedildi.'));reset();await refresh();setPostFilter(outcome==='submitted'?'pending_approval':outcome==='approved'&&schedule?'scheduled':'all');setView('posts')}catch(e:any){toast.error(t(e.message))}finally{setBusy(false)}}
function openDraft(p:any){setText(p.text);setSelected(p.platforms);setAssetId(p.asset?.id||null);setUploaded(p.asset||null);setRecipients((p.options.recipients||[]).join('\n'));setTemplate(p.options.template||'');setLanguage(p.options.language||'tr');setParams((p.options.template_params||[]).join('\n'));setWaMode(p.options.wa_mode||'template');setSessionConfirmed(false);setSchedule(p.scheduled_at&&p.scheduled_at>Date.now()/1000?zoneInput(p.scheduled_at,tz):'');setEditing(p.id);request.current={fingerprint:'',id:''};setView('compose');if(p.options.legacy_media_url)toast.info(t('Eski taslağın medya bağlantısı korunuyor. Göndermek için dosyayı yeni yükleme alanına ekle.'))}
function duplicate(p:any){if(!editing&&text.trim()&&!confirm(t('Kaydedilmemiş taslağın bu kopyayla değiştirilsin mi?')))return;openDraft(p);setEditing(null);setSchedule('');toast.info(t('Kopya oluşturuldu. Kaydettiğinde yeni bir içerik olarak eklenir.'))}
function composeAt(local:string){reset();setSchedule(local);setView('compose')}
function pickAsset(a:any){setUploaded(a);setAssetId(a.id);setPicking(false);setView('compose')}
async function switchCompany(id:string){refreshContext.current++;forgetState();setCompany(id);setLoading(true);setState(empty);reset(true);setView('compose');await refresh()}
async function logout(){refreshContext.current++;await api('logout',{}).catch(()=>{});forgetState();try{Object.keys(localStorage).filter(k=>k.startsWith('akis-draft:')).forEach(k=>localStorage.removeItem(k))}catch{};setText('');setToken('');setSession({authenticated:false});setState(empty);setLoading(false)}
if(invite)return <><Invite token={invite} onDone={()=>{setInvite('');forgetState();setState(empty);setLoading(true);loadSession()}}/><div className="login-theme"><ThemeSwitch/><div className="language-quick login-language" role="group" aria-label={t('Uygulama dili')}><button aria-pressed={uiLanguage==='tr'} onClick={()=>changeLanguage('tr')}>TR</button><button aria-pressed={uiLanguage==='en'} onClick={()=>changeLanguage('en')}>EN</button></div></div><Toaster richColors position="bottom-right"/></>;
if(!session?.authenticated)return <><Login loading={loading} onDone={()=>{setLoading(true);loadSession()}}/><div className="login-theme"><ThemeSwitch/><div className="language-quick login-language" role="group" aria-label={t('Uygulama dili')}><button aria-pressed={uiLanguage==='tr'} onClick={()=>changeLanguage('tr')}>TR</button><button aria-pressed={uiLanguage==='en'} onClick={()=>changeLanguage('en')}>EN</button></div></div><div className="login-install"><InstallHint/></div><Toaster richColors position="bottom-right"/></>;
const user=session.user,companies=user.companies||[],current=companies.find((c:any)=>c.id===state.company?.id);
const pending=state.posts.filter((p:any)=>p.status==='pending_approval').length;
document.title=(pending&&can('approve')?`(${pending}) `:'')+'Akış — '+t('Sosyal medya stüdyosu');
const headings:Record<string,[string,string]>={
compose:[t(editing?'İçeriği düzenle':'İçerik oluştur'),t(direct?'Kanallarını seç, içeriğini hazırla ve paylaşım zamanını belirle.':'İçeriğini hazırla ve onaya gönder. Onaylandığında yayımlanır.')],
posts:[t('Gönderiler'),t('Onay durumunu, gönderim adımlarını ve platform sonuçlarını buradan takip et.')],
calendar:[t('Takvim'),t('Planlı ve yayımlanan içerikler şirketin saat dilimine göre.')],
library:[t('Medya kütüphanesi'),t('Dosyalarını klasör ve etiketlerle düzenle; tekrar yüklemeden kullan.')],
connections:[t('Bağlantılar'),t('Bağlantı sürelerini ve yenileme durumlarını tek yerden yönet.')],
settings:[t('Ayarlar'),t('Dil, saat gösterimi ve platform bağlantı ayarları.')],
team:[t('Şirket yönetimi'),t('Ekibini, rolleri, onay kuralını ve işlem geçmişini yönet.')],
system:[t('Sistem yönetimi'),t('Şirketler, kuyruk, hatalar, depolama ve servis sağlığı.')],
account:[t('Hesabım'),t('Parolanı ve iki aşamalı girişi yönet.')]
};
const nav=[{id:'compose',name:t('İçerik oluştur'),icon:Plus,show:can('compose')},{id:'posts',name:t('Gönderiler'),icon:FileText,show:can('read'),count:pending||state.posts.length,alert:pending>0&&can('approve')},{id:'calendar',name:t('Takvim'),icon:CalendarDays,show:can('read')},{id:'library',name:t('Medya kütüphanesi'),icon:Images,show:can('read')},{id:'connections',name:t('Bağlantılar'),icon:Link2,show:can('connections')},{id:'settings',name:t('Ayarlar'),icon:Settings2,show:can('settings')}].filter(n=>n.show);
const adminNav=[{id:'team',name:t('Şirket yönetimi'),icon:Users,show:can('members')},{id:'system',name:t('Sistem yönetimi'),icon:Server,show:user.is_system_admin},{id:'account',name:t('Hesabım'),icon:UserRound,show:true}].filter(n=>n.show);
const expiring=state.connections.filter((c:any)=>(c.days_left!==null&&c.days_left<=7)||c.refresh_error);
const allNav=[...nav,...adminNav];
const limit=selected.includes('x')?280:selected.includes('instagram')?2200:0;
const scheduleLabel=schedule?inZone(Math.floor(new Date(schedule+':00Z').getTime()/1000),'UTC'):'';
const scheduleNow=zoneInput(Math.floor(Date.now()/1000),tz).slice(0,16),schedulePast=!!schedule&&schedule<=scheduleNow;
const scheduleDate=schedule.slice(0,10),scheduleHour=schedule.slice(11,13)||'00',scheduleMinute=schedule.slice(14,16)||'00';
function setSchedulePart(part:'date'|'hour'|'minute',value:string){if(part==='date'&&!value)return;setSchedule(`${part==='date'?value:scheduleDate}T${part==='hour'?value:scheduleHour}:${part==='minute'?value:scheduleMinute}`)}
function changeHourFormat(value:HourFormat){saveHourFormat(value);setHourFormat(value)}
function changeLanguage(value:Language){saveLanguage(value);setUiLanguage(value)}
const hour24=Number(scheduleHour),hour12=String((hour24+11)%12+1).padStart(2,'0'),period=hour24>=12?'PM':'AM';
function setTwelveHour(value:string,nextPeriod=period){const h=Number(value)%12+(nextPeriod==='PM'?12:0);setSchedulePart('hour',String(h).padStart(2,'0'))}
return <SidebarProvider><Sidebar className="app-sidebar"><SidebarHeader><a className="brand" href="/"><span className="brand-icon"><Layers3 size={25}/></span>akış<span className="brand-dot">.</span></a>
{companies.length>0?<label className="workspace company-switch"><span className="avatar">{(current?.name||'?').slice(0,1).toUpperCase()}</span><div><select aria-label={t('Şirket seç')} value={state.company?.id||''} onChange={e=>switchCompany(e.target.value)}>{companies.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><small>{current?t(roleNames[current.role]):''}</small></div></label>:<div className="workspace"><span className="avatar">S</span><div>{t('Şirket üyeliği yok')}<small>{t('Sistem yöneticisi')}</small></div></div>}
</SidebarHeader><SidebarContent>{nav.length>0&&<><div className="nav-label">{t('STÜDYO')}</div><SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} onClick={()=>{if(n.id==='posts')setPostFilter(pending&&can('approve')?'pending_approval':'all');setView(n.id)}}><n.icon/><span>{n.name}</span>{n.count!==undefined&&<span className={'nav-count '+(n.alert?'alert':'')}>{n.count}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></>}
<div className="nav-label">{t('YÖNETİM')}</div><SidebarMenu>{adminNav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} onClick={()=>setView(n.id)}><n.icon/><span>{n.name}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>
<div className="sidebar-note"><Radio size={20}/><strong>{t('Sen üret, Akış hazırlasın.')}</strong><p>{t('Medya dönüşümü, onaylar ve planlı paylaşımlar arka planda devam eder.')}</p></div></SidebarContent>
<SidebarFooter><ThemeSwitch/><div className="private"><ShieldCheck size={17}/>{t(user.totp_enabled?'İki aşamalı giriş açık':'Şifreli hesap bağlantıları')}</div><div className="workspace footer-profile"><span className="avatar">{(user.name||user.email).slice(0,1).toUpperCase()}</span><div className="profile-text">{user.name||user.email}<small>{user.email}</small></div><button className="icon-button" title={t('Çıkış yap')} aria-label={t('Çıkış yap')} onClick={logout}><LogOut size={16}/></button></div></SidebarFooter></Sidebar>
<SidebarInset><header className="topbar"><div><SidebarTrigger/><span>{state.company?.name||'Akış'}</span><span className="slash">/</span><strong>{allNav.find(n=>n.id===view)?.name}</strong></div><div className="topbar-meta"><div className="language-quick" role="group" aria-label={t('Uygulama dili')}><button aria-pressed={uiLanguage==='tr'} onClick={()=>changeLanguage('tr')}>TR</button><button aria-pressed={uiLanguage==='en'} onClick={()=>changeLanguage('en')}>EN</button></div><span className={'sync-status '+(!online||error?'sync-error':'')} role="status" aria-live="polite" title={lastSynced?`${t('Son güncelleme')}: ${new Date(lastSynced).toLocaleTimeString(uiLanguage==='en'?'en-US':'tr-TR')}`:t('Henüz güncellenmedi')}><RefreshCw className={refreshing?'spin':''} size={13}/>{t(!online?'Çevrimdışı':refreshing?'Güncelleniyor':error?'Bağlantı sorunu':'Güncel')}</span><span>{state.connections.length}/4 {t('platform bağlı')} · {tz}</span></div></header><main className="main"><InstallHint/><div className="page-heading"><div><div className="eyebrow">{t('SOSYAL MEDYA STÜDYOSU')}</div><h1>{headings[view]?.[0]}</h1><p>{headings[view]?.[1]}</p></div>{!['compose','system','account'].includes(view)&&can('compose')&&<button className="primary" onClick={()=>{reset();setView('compose')}}><Plus size={18}/>{t('Yeni içerik')}</button>}</div>
{error&&view!=='system'&&view!=='account'&&<div className="error" role="alert">{t(error)} <button onClick={refresh}>{t('Tekrar dene')}</button></div>}{expiring.length>0&&can('connections')&&view!=='connections'&&<div className="expiry expiry-warn"><RefreshCw size={17}/><span>{expiring.length} {t('bağlantının süresi veya yenilemesi dikkat gerektiriyor.')}</span><button className="inline-link" onClick={()=>setView('connections')}>{t('Bağlantıları incele')}</button></div>}
{pending>0&&can('approve')&&view!=='posts'&&view!=='compose'&&<div className="expiry"><Check size={17}/><span>{pending} {t('içerik onayını bekliyor.')}</span><button className="inline-link" onClick={()=>{setPostFilter('pending_approval');setView('posts')}}>{t('Onay listesini aç')}</button></div>}
<Suspense fallback={<div className="panel empty-state"><Loader2 className="spin"/><span>{t('Ekran hazırlanıyor…')}</span></div>}>
{view==='compose'&&can('compose')&&<div className="editor-grid"><section className="panel editor"><div className="panel-head"><h2><FileText size={18}/>{t(editing?'İçeriği düzenle':'Yeni içerik')}</h2>{editing?<button className="text-button" onClick={()=>reset()}><X size={14}/>{t('Düzenlemeyi bırak')}</button>:<span className="pill">{t('Taslak')}</span>}</div><div className="editor-body"><label className="field-title">{t('Nerede paylaşmak istersin?')}</label><div className="channels">{platforms.map(p=><button aria-pressed={selected.includes(p.id)} key={p.id} className={'channel '+(selected.includes(p.id)?'chosen':'')} onClick={()=>{setSelected(s=>s.includes(p.id)?s.filter(x=>x!==p.id):[...s,p.id]);setPreview(p.id)}}><span className="platform-icon" style={{background:p.color}}>{p.symbol}</span><span>{p.name}</span><span className="channel-check">{selected.includes(p.id)&&<Check size={13}/>}</span></button>)}</div><div className="label-row"><label htmlFor="content" className="field-title">{t('Paylaşım metni')}</label><span>{t('Senin sesin, senin içeriğin.')}</span></div><textarea id="content" value={text} onChange={e=>setText(e.target.value)} placeholder={t('Bugün dünyayla ne paylaşmak istersin?')} maxLength={5000}/><div className="editor-toolbar"><span><FileText size={15}/>{t('Metin ve bağlantılar')}</span><span className={limit&&text.length>limit?'warn':''}>{text.length}{limit?` / ${limit}`:` ${t('karakter')}`}</span></div><label className="field-title">{t('Görsel veya video')}</label><MediaUpload asset={asset} onUploaded={(a:any)=>{setUploaded(a);setAssetId(a.id);refresh()}} onRemove={()=>{setAssetId(null);setUploaded(null)}} onBusy={setUploading} maxMB={state.settings.max_upload_mb} onLibrary={()=>setPicking(true)}/>
{picking&&<div className="picker"><div className="picker-head"><h2>{t('Kütüphaneden seç')}</h2><button className="icon-button" aria-label={t('Kapat')} onClick={()=>setPicking(false)}><X size={16}/></button></div><Library can={can} picker onUse={pickAsset}/></div>}
{selected.includes('tiktok')&&<div className="notice"><FileText size={18}/><span>{t(asset?.mime_type?.startsWith('image')?'Bu görsel TikTok için otomatik olarak 4 saniyelik, 1080 × 1920 videoya çevrilecek.':'Görseller TikTok için 4 saniyelik dikey videoya çevrilir.')} {t('Son paylaşımı TikTok gelen kutusundan tamamlarsın.')}</span></div>}{selected.includes('whatsapp')&&<div className="wa-fields"><h2>{t('WhatsApp gönderimi')}</h2><Tabs value={waMode} onValueChange={setWaMode}><TabsList><TabsTrigger value="template">{t('Onaylı şablon')}</TabsTrigger><TabsTrigger value="session">{t('24 saatlik oturum')}</TabsTrigger></TabsList></Tabs><label>{t('Alıcı numaraları')}<textarea className="short-textarea" value={recipients} onChange={e=>setRecipients(e.target.value)} placeholder={t('905xxxxxxxxx — her satıra bir numara')}/></label>{waMode==='template'?<><label>{t('Onaylı şablon adı')}<input value={template} onChange={e=>setTemplate(e.target.value)} placeholder="hello_world"/></label><label>{t('Şablon dil kodu')}<input value={language} onChange={e=>setLanguage(e.target.value)}/></label><label>{t('Metin parametreleri · isteğe bağlı')}<textarea className="short-textarea" value={params} onChange={e=>setParams(e.target.value)} placeholder={t('Her satıra bir parametre, şablon sırasıyla')}/></label><p className="field-help">{t('Eklediğin medya şablonun başlığına yerleştirilir. Onaylı şablon başlığı aynı medya türünü desteklemeli.')}</p></>:<div className="notice"><Checkbox id="wa-window" checked={sessionConfirmed} onCheckedChange={v=>setSessionConfirmed(!!v)}/><label htmlFor="wa-window">{t('Alıcıların son 24 saat içinde bu işletmeye mesaj gönderdiğini doğruluyorum. Aksi halde onaylı şablon kullanmalıyım.')}</label></div>}</div>}
<div className="schedule-field"><label className="field-title" htmlFor="schedule-date"><CalendarClock size={16}/>{t('Paylaşım zamanı')}</label><div className="schedule-row"><Tabs value={schedule?'later':'now'} onValueChange={v=>setSchedule(v==='now'?'':zoneInput(Math.floor(Date.now()/1000)+3600,tz))}><TabsList><TabsTrigger value="now">{t(direct?'Hemen':'Onaylanınca')}</TabsTrigger><TabsTrigger value="later">{t('İleri tarihte')}</TabsTrigger></TabsList></Tabs>{schedule&&<div className="schedule-picker"><input id="schedule-date" aria-label={t('Paylaşım tarihi')} type="date" value={scheduleDate} min={scheduleNow.slice(0,10)} onChange={e=>setSchedulePart('date',e.target.value)}/><span className="schedule-clock" aria-label={t(hourFormat==='24'?'24 saat biçiminde paylaşım saati':'12 saat biçiminde paylaşım saati')}>{hourFormat==='24'?<select aria-label={t('Saat')} value={scheduleHour} onChange={e=>setSchedulePart('hour',e.target.value)}>{Array.from({length:24},(_,i)=><option key={i} value={String(i).padStart(2,'0')}>{String(i).padStart(2,'0')}</option>)}</select>:<><select aria-label={t('Saat')} value={hour12} onChange={e=>setTwelveHour(e.target.value)}>{Array.from({length:12},(_,i)=><option key={i} value={String(i+1).padStart(2,'0')}>{String(i+1).padStart(2,'0')}</option>)}</select></>}<b>:</b><select aria-label={t('Dakika')} value={scheduleMinute} onChange={e=>setSchedulePart('minute',e.target.value)}>{Array.from({length:60},(_,i)=><option key={i} value={String(i).padStart(2,'0')}>{String(i).padStart(2,'0')}</option>)}</select>{hourFormat==='12'&&<select aria-label={t('Öğleden önce veya sonra')} value={period} onChange={e=>setTwelveHour(hour12,e.target.value)}><option value="AM">AM</option><option value="PM">PM</option></select>}</span></div>}</div>{schedule&&<p className={'field-help '+(schedulePast?'warn':'')}>{schedulePast?`${t('Geçmiş bir saat seçilemez.')} `:''}{scheduleLabel} · {tz} {t('saatiyle.')} {direct?'':t('Onay bu zamandan önce verilmeli.')}</p>}</div>
<div className="notice"><ShieldCheck size={18}/><span>{t(direct?'Paylaşım her kanal için ayrı takip edilir. Geçici hatalarda üç otomatik yeniden deneme yapılır.':'Şirketinde onay zorunlu. Gönderdiğin içerik, onaylayan veya yönetici onayladıktan sonra yayımlanır.')}</span></div></div><div className="editor-footer"><button className="secondary" disabled={busy||uploading||loading||!!error||!selected.length} onClick={()=>save(false)}>{t('Taslağı kaydet')}</button><button className="primary" disabled={busy||uploading||loading||!!error||!selected.length||schedulePast||asset?.status==='failed'} onClick={()=>save(true)}>{busy?<Loader2 className="spin" size={17}/>:<Send size={17}/>}{t(!direct?'Onaya gönder':schedule?'Planla':'Paylaşımı başlat')}</button></div></section><aside><div className="preview-title"><h2>{t('Canlı önizleme')}</h2><span>{t('Yaklaşık görünüm')}</span></div><Tabs value={preview} onValueChange={setPreview}><TabsList className="preview-tabs">{platforms.map(p=><TabsTrigger key={p.id} value={p.id}>{p.symbol}<span className="sr-only">{p.name}</span></TabsTrigger>)}</TabsList>{platforms.map(p=><TabsContent value={p.id} key={p.id}><div className="social-preview"><div className="social-profile"><span className="social-avatar">a.</span><div><strong>{state.connections.find((c:any)=>c.platform===p.id)?.label||t('Senin hesabın')}</strong><small>{schedule?`${t('Planlı')}: ${scheduleLabel}`:t('Paylaşım önizlemesi')}</small></div><span className="social-brand">{p.symbol}</span></div><div className="preview-text">{p.id==='whatsapp'&&waMode==='template'?(template?`${t('Şablon')}: ${template}`:t('Onaylı şablon mesajın burada.')):(text||t('Güzel fikirler paylaşılmayı bekler.\nİçeriğini yazmaya başla ✨'))}</div>{asset?.url?<div className={'actual-preview '+(p.id==='tiktok'?'vertical':'')}>{asset.mime_type.startsWith('image')?<img src={mediaSrc(asset.url)} alt={t('Paylaşılacak medya')}/>:<video controls playsInline muted preload="metadata" src={mediaSrc(asset.url)}/>}</div>:<div className="preview-empty"><Layers3 size={36}/><span>{t(asset?'Medya hazırlanıyor…':'Fikrine yer aç.')}</span><small>{t('Dosyanı yükle, burada görüntüle.')}</small></div>}<div className="social-actions"><span>♡</span><span>◯</span><Send size={17}/><span className="bookmark">⌑</span></div></div></TabsContent>)}</Tabs><div className="tip-card"><Radio size={20}/><div><strong>{t('Formatla uğraşma.')}</strong><p>{t('Görseller JPEG’e dönüşür. Uygun olmayan oranlar, görsel kesilmeden kenarlık eklenerek düzenlenir.')}</p></div></div><div className="mini-summary"><span>{t('Seçili kanallar')}</span><strong>{selected.length} {t('platform')}</strong></div></aside></div>}
{view==='posts'&&<Posts key={postFilter} posts={state.posts} loading={loading} refresh={refresh} can={can} tz={tz} onEdit={openDraft} onDuplicate={can('compose')?duplicate:undefined} initialFilter={postFilter}/>}
{view==='calendar'&&<Calendar posts={state.posts} tz={tz} can={can} onCompose={composeAt} onEdit={openDraft}/>}
{view==='library'&&<Library can={can} maxMB={state.settings.max_upload_mb} onUse={can('compose')?(a:any)=>{reset();pickAsset(a)}:undefined}/>}
{view==='connections'&&can('connections')&&<Connections connections={state.connections} settings={state.settings} refresh={refresh} onSettings={()=>setView('settings')}/>}{view==='settings'&&can('settings')&&<Settings settings={state.settings} refresh={refresh} hourFormat={hourFormat} onHourFormat={changeHourFormat} language={uiLanguage} onLanguage={changeLanguage}/>}
{view==='team'&&can('members')&&<Team tz={tz} can={can} me={user} refreshState={refresh}/>}
{view==='system'&&user.is_system_admin&&<System settings={state.settings} refreshState={loadSession}/>}
{view==='account'&&<Account me={user} refreshSession={loadSession} hourFormat={hourFormat} onHourFormat={changeHourFormat} language={uiLanguage} onLanguage={changeLanguage}/>}
</Suspense>
<footer className="page-footer"><span>akış.</span><span>{t('Daha az sekme. Daha çok üretim.')}</span></footer></main></SidebarInset><Toaster richColors position="bottom-right"/></SidebarProvider>}
