import {useEffect,useState,useRef,useCallback} from 'react';
import {Send,Layers3,Link2,FileText,Plus,Check,ShieldCheck,Radio,Loader2,Settings2,RefreshCw,CalendarDays,Images,Users,Server,UserRound,LogOut,CalendarClock,X} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger} from '@/components/ui/sidebar';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {Toaster,toast} from 'sonner';
import {api,platforms,setCompany,roleNames,zoneInput,inZone} from './studio/api';
import Connections from './studio/Connections';
import Settings from './studio/Settings';
import MediaUpload from './studio/MediaUpload';
import Login from './studio/Login';
import Posts from './studio/Posts';
import Calendar from './studio/Calendar';
import Library from './studio/Library';
import Team from './studio/Team';
import System from './studio/System';
import Account from './studio/Account';
import {ThemeSwitch} from './studio/theme';
const empty={company:null,me:{role:null,permissions:[]},connections:[],posts:[],assets:[],settings:{oauth_apps:[],queue:'',app_origin:location.origin,max_upload_mb:100}};
export default function Home(){
const [view,setView]=useState('compose'),[text,setText]=useState(''),[selected,setSelected]=useState<string[]>(['x']),[preview,setPreview]=useState('x'),[state,setState]=useState<any>(empty),[assetId,setAssetId]=useState<string|null>(null),[uploaded,setUploaded]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[recipients,setRecipients]=useState(''),[template,setTemplate]=useState(''),[language,setLanguage]=useState('tr'),[params,setParams]=useState(''),[waMode,setWaMode]=useState('template'),[sessionConfirmed,setSessionConfirmed]=useState(false),[session,setSession]=useState<any>(null),[editing,setEditing]=useState<string|null>(null),[schedule,setSchedule]=useState(''),[picking,setPicking]=useState(false),[postFilter,setPostFilter]=useState('all');
const request=useRef({fingerprint:'',id:''});
const refresh=useCallback(async()=>{try{const j=await api('state');setState(j);setError('')}catch(e:any){setError(e.message)}finally{setLoading(false)}},[]);
const loadSession=useCallback(async()=>{try{const s=await api('session');const companies=s.user?.companies||[];const saved=(()=>{try{return localStorage.getItem('akis-company')}catch{return null}})();const active=companies.find((c:any)=>c.id===saved)||companies[0];if(active)setCompany(active.id);setSession(s);if(s.authenticated&&active)await refresh();else setLoading(false);if(s.user?.must_change_password)setView('account');else if(s.authenticated&&!active&&s.user?.is_system_admin)setView('system')}catch(e:any){setError(e.message);setLoading(false)}},[refresh]);
useEffect(()=>{loadSession()},[loadSession]);
useEffect(()=>{if(!session?.authenticated)return;const id=setInterval(()=>{if(!document.hidden)refresh()},4000);return()=>clearInterval(id)},[session?.authenticated,refresh]);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();try{Promise.resolve(context.registerTool({name:'stage_content',description:'Prepare text in the content editor without saving or publishing.',inputSchema:{type:'object',properties:{text:{type:'string',maxLength:5000}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input:any){if(typeof input?.text!=='string'||input.text.length>5000)throw Error('Geçersiz metin');setText(input.text);setView('compose');return {staged:true,published:false}}},{signal:life.signal})).catch(()=>{})}catch{}return()=>life.abort()},[]);
const perms:string[]=state.me?.permissions||[];const can=useCallback((p:string)=>perms.includes(p),[perms.join()]);
const tz=state.company?.timezone||'Europe/Istanbul';
const asset=state.assets.find((a:any)=>a.id===assetId)||(uploaded?.id===assetId?uploaded:null);
const direct=can('approve')||state.company?.require_approval===false;
function reset(){request.current={fingerprint:'',id:''};setText('');setAssetId(null);setUploaded(null);setEditing(null);setSchedule('')}
async function save(send:boolean){setBusy(true);const body={text,platforms:selected,asset_id:assetId,send,scheduled_local:schedule,recipients:recipients.split(/[\s,;]+/).filter(Boolean),template,language,template_params:params.split('\n').filter(Boolean),wa_mode:waMode,session_confirmed:sessionConfirmed};const fingerprint=JSON.stringify(body);if(request.current.fingerprint!==fingerprint)request.current={fingerprint,id:crypto.randomUUID()};try{const r=editing?await api('posts/'+editing,body,'PUT'):await api('posts',{...body,requestId:request.current.id});const outcome=r.outcome||(send?'approved':'draft');toast.success(outcome==='submitted'?'Onaya gönderildi. Yetkili onayladığında yayımlanacak.':outcome==='approved'?(schedule?'Planlandı. Belirlenen zamanda gönderilecek.':'Gönderim kuyruğuna eklendi. Akış arka planda devam ediyor.'):'Taslak kaydedildi.');reset();await refresh();setPostFilter(outcome==='submitted'?'pending_approval':outcome==='approved'&&schedule?'scheduled':'all');setView('posts')}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
function openDraft(p:any){setText(p.text);setSelected(p.platforms);setAssetId(p.asset?.id||null);setUploaded(p.asset||null);setRecipients((p.options.recipients||[]).join('\n'));setTemplate(p.options.template||'');setLanguage(p.options.language||'tr');setParams((p.options.template_params||[]).join('\n'));setWaMode(p.options.wa_mode||'template');setSessionConfirmed(false);setSchedule(p.scheduled_at&&p.scheduled_at>Date.now()/1000?zoneInput(p.scheduled_at,tz):'');setEditing(p.id);request.current={fingerprint:'',id:''};setView('compose');if(p.options.legacy_media_url)toast.info('Eski taslağın medya bağlantısı korunuyor. Göndermek için dosyayı yeni yükleme alanına ekle.')}
function composeAt(local:string){reset();setSchedule(local);setView('compose')}
function pickAsset(a:any){setUploaded(a);setAssetId(a.id);setPicking(false);setView('compose')}
async function switchCompany(id:string){setCompany(id);setLoading(true);setState(empty);reset();setView('compose');await refresh()}
async function logout(){await api('logout',{});setSession({authenticated:false});setState(empty);setLoading(false)}
if(!session?.authenticated)return <><Login loading={loading} onDone={()=>{setLoading(true);loadSession()}}/><div className="login-theme"><ThemeSwitch/></div><Toaster richColors position="bottom-right"/></>;
const user=session.user,companies=user.companies||[],current=companies.find((c:any)=>c.id===state.company?.id);
const pending=state.posts.filter((p:any)=>p.status==='pending_approval').length;
const headings:Record<string,[string,string]>={compose:[editing?'İçeriği düzenle.':'Sıradaki paylaşımın burada başlıyor.',direct?'Dosyanı bırak, kanallarını seç. İstersen ileri bir tarihe planla.':'İçeriğini hazırla ve onaya gönder. Onaylandığında yayımlanır.'],posts:['İçeriklerin, tek bir yerde.','Onay durumunu, gönderim adımlarını ve platform sonuçlarını buradan takip et.'],calendar:['Paylaşım takvimi.','Planlı ve yayımlanan içerikler şirketin saat dilimine göre.'],library:['Medya kütüphanesi.','Dosyalarını klasör ve etiketlerle düzenle; tekrar yüklemeden kullan.'],connections:['Kanallarını Akış’a bağla.','Bağlantı sürelerini ve yenileme durumlarını tek yerden yönet.'],settings:['Stüdyonun bağlantı ayarları.','Platform uygulama bilgileri ve dönüş adresleri.'],team:['Şirket yönetimi.','Ekibini, rolleri, onay kuralını ve işlem geçmişini yönet.'],system:['Sistem yönetimi.','Şirketler, kuyruk, hatalar, depolama ve servis sağlığı.'],account:['Hesabım.','Parolanı ve iki aşamalı girişi yönet.']};
const nav=[{id:'compose',name:'İçerik oluştur',icon:Plus,show:can('compose')},{id:'posts',name:'Gönderiler',icon:FileText,show:can('read'),count:pending||state.posts.length,alert:pending>0&&can('approve')},{id:'calendar',name:'Takvim',icon:CalendarDays,show:can('read')},{id:'library',name:'Medya kütüphanesi',icon:Images,show:can('read')},{id:'connections',name:'Bağlantılar',icon:Link2,show:can('connections')},{id:'settings',name:'Ayarlar',icon:Settings2,show:can('settings')}].filter(n=>n.show);
const adminNav=[{id:'team',name:'Şirket yönetimi',icon:Users,show:can('members')},{id:'system',name:'Sistem yönetimi',icon:Server,show:user.is_system_admin},{id:'account',name:'Hesabım',icon:UserRound,show:true}].filter(n=>n.show);
const expiring=state.connections.filter((c:any)=>(c.days_left!==null&&c.days_left<=7)||c.refresh_error);
const allNav=[...nav,...adminNav];
const scheduleLabel=schedule?inZone(Math.floor(new Date(schedule+':00Z').getTime()/1000),'UTC'):'';
return <SidebarProvider><Sidebar className="app-sidebar"><SidebarHeader><a className="brand" href="/"><span className="brand-icon"><Layers3 size={25}/></span>akış<span className="brand-dot">.</span></a>
{companies.length>0?<label className="workspace company-switch"><span className="avatar">{(current?.name||'?').slice(0,1).toUpperCase()}</span><div><select aria-label="Şirket seç" value={state.company?.id||''} onChange={e=>switchCompany(e.target.value)}>{companies.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><small>{current?roleNames[current.role]:''}</small></div></label>:<div className="workspace"><span className="avatar">S</span><div>Şirket üyeliği yok<small>Sistem yöneticisi</small></div></div>}
</SidebarHeader><SidebarContent>{nav.length>0&&<><div className="nav-label">STÜDYO</div><SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} onClick={()=>{if(n.id==='posts')setPostFilter(pending&&can('approve')?'pending_approval':'all');setView(n.id)}}><n.icon/><span>{n.name}</span>{n.count!==undefined&&<span className={'nav-count '+(n.alert?'alert':'')}>{n.count}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></>}
<div className="nav-label">YÖNETİM</div><SidebarMenu>{adminNav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} onClick={()=>setView(n.id)}><n.icon/><span>{n.name}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>
<div className="sidebar-note"><Radio size={20}/><strong>Sen üret, Akış hazırlasın.</strong><p>Medya dönüşümü, onaylar ve planlı paylaşımlar arka planda devam eder.</p></div></SidebarContent>
<SidebarFooter><ThemeSwitch/><div className="private"><ShieldCheck size={17}/>{user.totp_enabled?'İki aşamalı giriş açık':'Şifreli hesap bağlantıları'}</div><div className="workspace footer-profile"><span className="avatar">{(user.name||user.email).slice(0,1).toUpperCase()}</span><div className="profile-text">{user.name||user.email}<small>{user.email}</small></div><button className="icon-button" title="Çıkış yap" aria-label="Çıkış yap" onClick={logout}><LogOut size={16}/></button></div></SidebarFooter></Sidebar>
<SidebarInset><header className="topbar"><div><SidebarTrigger/><span>{state.company?.name||'Akış'}</span><span className="slash">/</span><strong>{allNav.find(n=>n.id===view)?.name}</strong></div><span>{state.connections.length}/4 platform bağlı · {tz}</span></header><main className="main"><div className="page-heading"><div><div className="eyebrow">SOSYAL MEDYA STÜDYOSU</div><h1>{headings[view]?.[0]}</h1><p>{headings[view]?.[1]}</p></div>{!['compose','system','account'].includes(view)&&can('compose')&&<button className="primary" onClick={()=>{reset();setView('compose')}}><Plus size={18}/>Yeni içerik</button>}</div>
{error&&view!=='system'&&view!=='account'&&<div className="error" role="alert">{error} <button onClick={refresh}>Tekrar dene</button></div>}{expiring.length>0&&can('connections')&&view!=='connections'&&<div className="expiry expiry-warn"><RefreshCw size={17}/><span>{expiring.length} bağlantının süresi veya yenilemesi dikkat gerektiriyor.</span><button className="inline-link" onClick={()=>setView('connections')}>Bağlantıları incele</button></div>}
{pending>0&&can('approve')&&view!=='posts'&&view!=='compose'&&<div className="expiry"><Check size={17}/><span>{pending} içerik onayını bekliyor.</span><button className="inline-link" onClick={()=>{setPostFilter('pending_approval');setView('posts')}}>Onay listesini aç</button></div>}
{view==='compose'&&can('compose')&&<div className="editor-grid"><section className="panel editor"><div className="panel-head"><h2><FileText size={18}/>{editing?'İçeriği düzenle':'Yeni içerik'}</h2>{editing?<button className="text-button" onClick={reset}><X size={14}/>Düzenlemeyi bırak</button>:<span className="pill">Taslak</span>}</div><div className="editor-body"><label className="field-title">Nerede paylaşmak istersin?</label><div className="channels">{platforms.map(p=><button aria-pressed={selected.includes(p.id)} key={p.id} className={'channel '+(selected.includes(p.id)?'chosen':'')} onClick={()=>{setSelected(s=>s.includes(p.id)?s.filter(x=>x!==p.id):[...s,p.id]);setPreview(p.id)}}><span className="platform-icon" style={{background:p.color}}>{p.symbol}</span><span>{p.name}</span><span className="channel-check">{selected.includes(p.id)&&<Check size={13}/>}</span></button>)}</div><div className="label-row"><label htmlFor="content" className="field-title">Paylaşım metni</label><span>Senin sesin, senin içeriğin.</span></div><textarea id="content" value={text} onChange={e=>setText(e.target.value)} placeholder="Bugün dünyayla ne paylaşmak istersin?" maxLength={5000}/><div className="editor-toolbar"><span><FileText size={15}/>Metin ve bağlantılar</span><span className={selected.includes('x')&&text.length>280?'warn':''}>{text.length}{selected.includes('x')?' / 280':' karakter'}</span></div><label className="field-title">Görsel veya video</label><MediaUpload asset={asset} onUploaded={(a:any)=>{setUploaded(a);setAssetId(a.id);refresh()}} onRemove={()=>{setAssetId(null);setUploaded(null)}} onBusy={setUploading} maxMB={state.settings.max_upload_mb} onLibrary={()=>setPicking(true)}/>
{picking&&<div className="picker"><div className="picker-head"><h2>Kütüphaneden seç</h2><button className="icon-button" aria-label="Kapat" onClick={()=>setPicking(false)}><X size={16}/></button></div><Library can={can} picker onUse={pickAsset}/></div>}
{selected.includes('tiktok')&&<div className="notice"><FileText size={18}/><span>{asset?.mime_type?.startsWith('image')?'Bu görsel TikTok için otomatik olarak 4 saniyelik, 1080 × 1920 videoya çevrilecek.':'Görseller TikTok için 4 saniyelik dikey videoya çevrilir.'} Son paylaşımı TikTok gelen kutusundan tamamlarsın.</span></div>}{selected.includes('whatsapp')&&<div className="wa-fields"><h2>WhatsApp gönderimi</h2><Tabs value={waMode} onValueChange={setWaMode}><TabsList><TabsTrigger value="template">Onaylı şablon</TabsTrigger><TabsTrigger value="session">24 saatlik oturum</TabsTrigger></TabsList></Tabs><label>Alıcı numaraları<textarea className="short-textarea" value={recipients} onChange={e=>setRecipients(e.target.value)} placeholder="905xxxxxxxxx — her satıra bir numara"/></label>{waMode==='template'?<><label>Onaylı şablon adı<input value={template} onChange={e=>setTemplate(e.target.value)} placeholder="hello_world"/></label><label>Şablon dil kodu<input value={language} onChange={e=>setLanguage(e.target.value)}/></label><label>Metin parametreleri · isteğe bağlı<textarea className="short-textarea" value={params} onChange={e=>setParams(e.target.value)} placeholder="Her satıra bir parametre, şablon sırasıyla"/></label><p className="field-help">Eklediğin medya şablonun başlığına yerleştirilir. Onaylı şablon başlığı aynı medya türünü desteklemeli.</p></>:<div className="notice"><Checkbox id="wa-window" checked={sessionConfirmed} onCheckedChange={v=>setSessionConfirmed(!!v)}/><label htmlFor="wa-window">Alıcıların son 24 saat içinde bu işletmeye mesaj gönderdiğini doğruluyorum. Aksi halde onaylı şablon kullanmalıyım.</label></div>}</div>}
<div className="schedule-field"><label className="field-title" htmlFor="schedule"><CalendarClock size={16}/>Paylaşım zamanı</label><div className="schedule-row"><Tabs value={schedule?'later':'now'} onValueChange={v=>setSchedule(v==='now'?'':zoneInput(Math.floor(Date.now()/1000)+3600,tz))}><TabsList><TabsTrigger value="now">{direct?'Hemen':'Onaylanınca'}</TabsTrigger><TabsTrigger value="later">İleri tarihte</TabsTrigger></TabsList></Tabs>{schedule&&<input id="schedule" type="datetime-local" value={schedule} min={zoneInput(Math.floor(Date.now()/1000),tz)} onChange={e=>setSchedule(e.target.value)}/>}</div>{schedule&&<p className="field-help">{scheduleLabel} · {tz} saatiyle. {direct?'':'Onay bu zamandan önce verilmeli.'}</p>}</div>
<div className="notice"><ShieldCheck size={18}/><span>{direct?'Paylaşım her kanal için ayrı takip edilir. Geçici hatalarda üç otomatik yeniden deneme yapılır.':'Şirketinde onay zorunlu. Gönderdiğin içerik, onaylayan veya yönetici onayladıktan sonra yayımlanır.'}</span></div></div><div className="editor-footer"><button className="secondary" disabled={busy||uploading||loading||!!error||!selected.length} onClick={()=>save(false)}>Taslağı kaydet</button><button className="primary" disabled={busy||uploading||loading||!!error||!selected.length||asset?.status==='failed'} onClick={()=>save(true)}>{busy?<Loader2 className="spin" size={17}/>:<Send size={17}/>}{!direct?'Onaya gönder':schedule?'Planla':'Paylaşımı başlat'}</button></div></section><aside><div className="preview-title"><h2>Canlı önizleme</h2><span>Yaklaşık görünüm</span></div><Tabs value={preview} onValueChange={setPreview}><TabsList className="preview-tabs">{platforms.map(p=><TabsTrigger key={p.id} value={p.id}>{p.symbol}<span className="sr-only">{p.name}</span></TabsTrigger>)}</TabsList>{platforms.map(p=><TabsContent value={p.id} key={p.id}><div className="social-preview"><div className="social-profile"><span className="social-avatar">a.</span><div><strong>{state.connections.find((c:any)=>c.platform===p.id)?.label||'Senin hesabın'}</strong><small>{schedule?'Planlı: '+scheduleLabel:'Paylaşım önizlemesi'}</small></div><span className="social-brand">{p.symbol}</span></div><div className="preview-text">{p.id==='whatsapp'&&waMode==='template'?(template?'Şablon: '+template:'Onaylı şablon mesajın burada.'):(text||'Güzel fikirler paylaşılmayı bekler.\nİçeriğini yazmaya başla ✨')}</div>{asset?.url?<div className={'actual-preview '+(p.id==='tiktok'?'vertical':'')}>{asset.mime_type.startsWith('image')?<img src={asset.url} alt="Paylaşılacak medya"/>:<video controls playsInline muted preload="metadata" src={asset.url}/>}</div>:<div className="preview-empty"><Layers3 size={36}/><span>{asset?'Medya hazırlanıyor…':'Fikrine yer aç.'}</span><small>Dosyanı yükle, burada görüntüle.</small></div>}<div className="social-actions"><span>♡</span><span>◯</span><Send size={17}/><span className="bookmark">⌑</span></div></div></TabsContent>)}</Tabs><div className="tip-card"><Radio size={20}/><div><strong>Formatla uğraşma.</strong><p>Görseller JPEG’e dönüşür. Uygun olmayan oranlar, görsel kesilmeden kenarlık eklenerek düzenlenir.</p></div></div><div className="mini-summary"><span>Seçili kanallar</span><strong>{selected.length} platform</strong></div></aside></div>}
{view==='posts'&&<Posts key={postFilter} posts={state.posts} loading={loading} refresh={refresh} can={can} tz={tz} onEdit={openDraft} initialFilter={postFilter}/>}
{view==='calendar'&&<Calendar posts={state.posts} tz={tz} can={can} onCompose={composeAt} onEdit={openDraft}/>}
{view==='library'&&<Library can={can} maxMB={state.settings.max_upload_mb} onUse={can('compose')?(a:any)=>{reset();pickAsset(a)}:undefined}/>}
{view==='connections'&&can('connections')&&<Connections connections={state.connections} settings={state.settings} refresh={refresh} onSettings={()=>setView('settings')}/>}{view==='settings'&&can('settings')&&<Settings settings={state.settings} refresh={refresh}/>}
{view==='team'&&can('members')&&<Team tz={tz} can={can} me={user} refreshState={refresh}/>}
{view==='system'&&user.is_system_admin&&<System settings={state.settings} refreshState={loadSession}/>}
{view==='account'&&<Account me={user} refreshSession={loadSession}/>}
<footer className="page-footer"><span>akış.</span><span>Daha az sekme. Daha çok üretim.</span></footer></main></SidebarInset><Toaster richColors position="bottom-right"/></SidebarProvider>}
