"""content media credential queue schema

Revision ID: 82c6deb108cb
Revises: 
"""
from alembic import op
import sqlalchemy as sa

revision = '82c6deb108cb'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('contents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contents_created_by'), ['created_by'], unique=False)

    op.create_table('credentials',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('account_label', sa.String(length=120), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('refresh_expires_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.Column('refresh_error', sa.Text(), nullable=True),
    sa.Column('token_kind', sa.String(length=30), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner', 'platform', name='uq_credential_owner_platform')
    )
    op.create_table('oauth_apps',
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.String(length=250), nullable=False),
    sa.Column('client_secret', sa.Text(), nullable=True),
    sa.Column('redirect_uri', sa.String(length=600), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('platform')
    )
    op.create_table('oauth_states',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('session_hash', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('verifier', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broadcast',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('template_id', sa.String(length=150), nullable=False),
    sa.Column('recipient_list', sa.JSON(), nullable=False),
    sa.Column('content_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sent_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id')
    )
    op.create_table('content_platforms',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('content_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('recipient', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('external_post_id', sa.String(length=200), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.Integer(), nullable=True),
    sa.Column('next_attempt_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=False),
    sa.Column('final_request_started', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'platform', 'recipient', name='uq_content_target')
    )
    with op.batch_alter_table('content_platforms', schema=None) as batch_op:
        batch_op.create_index('idx_delivery_due', ['status', 'next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_platforms_content_id'), ['content_id'], unique=False)

    op.create_table('media_assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('content_id', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=180), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('is_auto_generated', sa.Boolean(), nullable=False),
    sa.Column('source_asset_id', sa.String(length=64), nullable=True),
    sa.Column('variant', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_asset_id', 'variant', name='uq_asset_variant')
    )
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_assets_owner'), ['owner'], unique=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_assets_owner'))

    op.drop_table('media_assets')
    with op.batch_alter_table('content_platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_platforms_content_id'))
        batch_op.drop_index('idx_delivery_due')

    op.drop_table('content_platforms')
    op.drop_table('broadcast')
    op.drop_table('oauth_states')
    op.drop_table('oauth_apps')
    op.drop_table('credentials')
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contents_created_by'))

    op.drop_table('contents')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
